'use server';

/**
 * @fileOverview Generates an initial draft of a note based on a user prompt.
 *
 * - generateInitialDraft - A function that generates an initial draft of a note.
 * - GenerateInitialDraftInput - The input type for the generateInitialDraft function.
 * - GenerateInitialDraftOutput - The return type for the generateInitialDraft function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateInitialDraftInputSchema = z.object({
  prompt: z.string().describe('A short prompt describing the desired note content.'),
});
export type GenerateInitialDraftInput = z.infer<typeof GenerateInitialDraftInputSchema>;

const GenerateInitialDraftOutputSchema = z.object({
  draft: z.string().describe('The initial draft of the note generated by the AI.'),
});
export type GenerateInitialDraftOutput = z.infer<typeof GenerateInitialDraftOutputSchema>;

export async function generateInitialDraft(input: GenerateInitialDraftInput): Promise<GenerateInitialDraftOutput> {
  return generateInitialDraftFlow(input);
}

const initialDraftPrompt = ai.definePrompt({
  name: 'initialDraftPrompt',
  input: {schema: GenerateInitialDraftInputSchema},
  output: {schema: GenerateInitialDraftOutputSchema},
  prompt: `You are a helpful AI assistant that generates initial drafts of notes based on user prompts.

  Prompt: {{{prompt}}}

  Please generate an initial draft of the note based on the prompt above. The draft should be well-written and informative.
  The response must be plain text, with markdown formatting if appropriate. Do not include any conversational prefixes such as \"Sure, here is a draft for you\". Just output the draft.
  `,
});

const generateInitialDraftFlow = ai.defineFlow(
  {
    name: 'generateInitialDraftFlow',
    inputSchema: GenerateInitialDraftInputSchema,
    outputSchema: GenerateInitialDraftOutputSchema,
  },
  async input => {
    const {output} = await initialDraftPrompt(input);
    return output!;
  }
);
