import type { Lang } from '@/app/languages';

export const authRequiredReleaseCopy: Record<Lang, { release050: string; warning: string }> = {
  en: { release050: 'Google sign-in is now required. Removed the editable guest preview. If authentication is lost, unsaved edits stay on this page for the original account and are reconciled with server changes after signing in again.', warning: 'Google sign-in is required. Wait for “Saved” before closing. Held unsaved edits are lost if you reload or close the page.' },
  ja: { release050: 'Googleログインを必須にし, 未ログインで編集できるPreviewを撤廃しました. 認証喪失時は未保存編集を元アカウント専用にページ内で保留し, 再ログイン後にサーバー側の変更と照合して復旧します.', warning: '利用にはGoogleログインが必要です. 閉じる前に「保存済み」を確認してください. 保留中の未保存編集は, 再読み込みやページを閉じると失われます.' },
  'zh-CN': { release050: '现在必须使用Google登录. 已移除可编辑的访客预览. 登录失效时, 未保存的编辑会在此页面中为原账户保留, 再次登录后与服务器更改核对并恢复.', warning: '使用前须登录Google. 关闭前请确认“已保存”. 刷新或关闭页面会丢失保留的未保存编辑.' },
  ko: { release050: 'Google 로그인이 필수가 되었습니다. 편집 가능한 게스트 미리보기를 제거했습니다. 인증이 끊기면 저장하지 않은 편집을 원래 계정 전용으로 페이지에 보관하고, 재로그인 후 서버 변경 사항과 대조하여 복구합니다.', warning: 'Google 로그인이 필요합니다. 닫기 전에 “저장됨”을 확인하세요. 새로고침하거나 페이지를 닫으면 보관 중인 미저장 편집이 사라집니다.' },
  es: { release050: 'Ahora se requiere iniciar sesión con Google. Eliminamos la vista previa editable para invitados. Si se pierde la autenticación, los cambios sin guardar permanecen en esta página para la cuenta original y se concilian con los cambios del servidor al volver a iniciar sesión.', warning: 'Se requiere iniciar sesión con Google. Confirma “Guardado” antes de cerrar. Recargar o cerrar la página elimina los cambios sin guardar retenidos.' },
  fr: { release050: 'La connexion Google est désormais obligatoire. L’aperçu modifiable pour les invités a été supprimé. Si l’authentification est perdue, les modifications non enregistrées restent dans cette page pour le compte d’origine et sont conciliées avec les changements du serveur à la reconnexion.', warning: 'La connexion Google est obligatoire. Vérifiez “Enregistré” avant de fermer. Recharger ou fermer la page efface les modifications non enregistrées en attente.' },
  'pt-BR': { release050: 'O login com Google agora é obrigatório. Removemos a prévia editável para visitantes. Se a autenticação for perdida, as alterações não salvas ficam nesta página para a conta original e são conciliadas com as mudanças do servidor ao entrar novamente.', warning: 'O login com Google é obrigatório. Confirme “Salvo” antes de fechar. Recarregar ou fechar a página elimina as alterações não salvas retidas.' },
  hi: { release050: 'अब Google से साइन इन करना आवश्यक है. अतिथियों का संपादन योग्य पूर्वावलोकन हटा दिया गया है. प्रमाणीकरण खोने पर बिना सहेजे बदलाव मूल खाते के लिए इसी पेज पर रखे जाते हैं और दोबारा साइन इन करने पर सर्वर के बदलावों से मिलान करके बहाल किए जाते हैं.', warning: 'Google से साइन इन करना आवश्यक है. बंद करने से पहले “सहेजा गया” की पुष्टि करें. पेज दोबारा लोड या बंद करने पर रखे गए बिना सहेजे बदलाव खो जाते हैं.' },
  ar: { release050: 'أصبح تسجيل الدخول باستخدام Google مطلوبًا. أزلنا المعاينة القابلة للتحرير للضيوف. عند فقدان المصادقة، تبقى التعديلات غير المحفوظة في الصفحة للحساب الأصلي وتُطابق مع تغييرات الخادم عند تسجيل الدخول مجددًا.', warning: 'يلزم تسجيل الدخول باستخدام Google. تحقق من “تم الحفظ” قبل الإغلاق. إعادة تحميل الصفحة أو إغلاقها يفقد التعديلات غير المحفوظة المحتفظ بها.' },
  ru: { release050: 'Теперь требуется вход через Google. Редактируемый гостевой просмотр удалён. При потере авторизации несохранённые изменения остаются на странице для исходного аккаунта и согласуются с изменениями сервера после повторного входа.', warning: 'Требуется вход через Google. Перед закрытием проверьте “Сохранено”. Перезагрузка или закрытие страницы удаляет удерживаемые несохранённые изменения.' },
  id: { release050: 'Login Google kini wajib. Pratinjau tamu yang dapat diedit telah dihapus. Jika autentikasi hilang, perubahan yang belum disimpan ditahan di halaman ini untuk akun asal dan dicocokkan dengan perubahan server setelah login kembali.', warning: 'Login Google diperlukan. Pastikan “Tersimpan” sebelum menutup. Memuat ulang atau menutup halaman menghilangkan perubahan yang belum disimpan yang ditahan.' },
};
