import type { Lang } from '@/app/languages';
import type { AccountLabels } from '@/components/account-menu';

type Copy = AccountLabels & { loginConfirm: string; discardConfirm: string };
type Words = [account: string, login: string, logout: string, retry: string, reload: string, guest: string, loading: string, pending: string, saving: string, saved: string, error: string, conflict: string, loginConfirm: string, discardConfirm: string];
function copy([account, login, logout, retry, reload, guest, loading, pending, saving, saved, error, conflict, loginConfirm, discardConfirm]: Words): Copy {
  return { account, login, logout, retry, reload, status: { guest, loading, pending, saving, saved, error, conflict }, loginConfirm, discardConfirm };
}
export const cloudCopy: Record<Lang, Copy> = {
  en: copy(['Account', 'Sign in with Google', 'Sign out', 'Retry', 'Load server version', 'Not saved', 'Loading', 'Unsaved changes', 'Saving', 'Saved', 'Could not save or load', 'Changes found on another device', 'If this account already has saved memos, they will replace this preview. Continue?', 'Discard unsaved changes and load the server version?']),
  ja: copy(['アカウント', 'Googleでログイン', 'ログアウト', '再試行', 'サーバーの内容を読み込む', '未保存', '読み込み中', '未保存の変更あり', '保存中', '保存済み', '保存または読み込みに失敗', '別の端末で変更されています', 'このアカウントに保存済みのメモがある場合, 現在のプレビューを置き換えます. 続けますか?', '未保存の変更を破棄し, サーバーの内容を読み込みますか?']),
  'zh-CN': copy(['账户', '使用Google登录', '退出登录', '重试', '加载服务器版本', '未保存', '正在加载', '有未保存的更改', '正在保存', '已保存', '保存或加载失败', '其他设备上有更改', '如果此账户已有保存的备忘录，它们将替换当前预览。是否继续？', '放弃未保存的更改并加载服务器版本？']),
  ko: copy(['계정', 'Google로 로그인', '로그아웃', '다시 시도', '서버 버전 불러오기', '저장되지 않음', '불러오는 중', '저장하지 않은 변경 사항', '저장 중', '저장됨', '저장 또는 불러오기 실패', '다른 기기에서 변경됨', '이 계정에 저장된 메모가 있으면 현재 미리보기를 대체합니다. 계속할까요?', '저장하지 않은 변경 사항을 버리고 서버 버전을 불러올까요?']),
  es: copy(['Cuenta', 'Iniciar sesión con Google', 'Cerrar sesión', 'Reintentar', 'Cargar versión del servidor', 'Sin guardar', 'Cargando', 'Cambios sin guardar', 'Guardando', 'Guardado', 'Error al guardar o cargar', 'Hay cambios en otro dispositivo', 'Si esta cuenta ya tiene notas guardadas, sustituirán esta vista previa. ¿Continuar?', '¿Descartar los cambios sin guardar y cargar la versión del servidor?']),
  fr: copy(['Compte', 'Se connecter avec Google', 'Se déconnecter', 'Réessayer', 'Charger la version du serveur', 'Non enregistré', 'Chargement', 'Modifications non enregistrées', 'Enregistrement', 'Enregistré', 'Échec de l’enregistrement ou du chargement', 'Modifications sur un autre appareil', 'Si ce compte contient déjà des notes enregistrées, elles remplaceront cet aperçu. Continuer ?', 'Abandonner les modifications non enregistrées et charger la version du serveur ?']),
  'pt-BR': copy(['Conta', 'Entrar com o Google', 'Sair', 'Tentar novamente', 'Carregar versão do servidor', 'Não salvo', 'Carregando', 'Alterações não salvas', 'Salvando', 'Salvo', 'Falha ao salvar ou carregar', 'Alterações em outro dispositivo', 'Se esta conta já tiver notas salvas, elas substituirão esta prévia. Continuar?', 'Descartar alterações não salvas e carregar a versão do servidor?']),
  hi: copy(['खाता', 'Google से साइन इन करें', 'साइन आउट करें', 'फिर कोशिश करें', 'सर्वर का संस्करण लोड करें', 'सहेजा नहीं गया', 'लोड हो रहा है', 'बदलाव सहेजे नहीं गए', 'सहेजा जा रहा है', 'सहेजा गया', 'सहेजने या लोड करने में विफल', 'दूसरे डिवाइस पर बदलाव हुए हैं', 'यदि इस खाते में पहले से सहेजे गए नोट हैं, तो वे इस पूर्वावलोकन की जगह ले लेंगे। जारी रखें?', 'बिना सहेजे बदलाव छोड़कर सर्वर का संस्करण लोड करें?']),
  ar: copy(['الحساب', 'تسجيل الدخول باستخدام Google', 'تسجيل الخروج', 'إعادة المحاولة', 'تحميل نسخة الخادم', 'غير محفوظ', 'جارٍ التحميل', 'تغييرات غير محفوظة', 'جارٍ الحفظ', 'تم الحفظ', 'تعذر الحفظ أو التحميل', 'توجد تغييرات على جهاز آخر', 'إذا كان هذا الحساب يحتوي على ملاحظات محفوظة، فستحل محل المعاينة الحالية. هل تريد المتابعة؟', 'هل تريد تجاهل التغييرات غير المحفوظة وتحميل نسخة الخادم؟']),
  ru: copy(['Аккаунт', 'Войти через Google', 'Выйти', 'Повторить', 'Загрузить версию с сервера', 'Не сохранено', 'Загрузка', 'Есть несохранённые изменения', 'Сохранение', 'Сохранено', 'Не удалось сохранить или загрузить', 'Есть изменения на другом устройстве', 'Если в этом аккаунте уже есть сохранённые заметки, они заменят текущий просмотр. Продолжить?', 'Отменить несохранённые изменения и загрузить версию с сервера?']),
  id: copy(['Akun', 'Masuk dengan Google', 'Keluar', 'Coba lagi', 'Muat versi server', 'Belum disimpan', 'Memuat', 'Perubahan belum disimpan', 'Menyimpan', 'Tersimpan', 'Gagal menyimpan atau memuat', 'Ada perubahan di perangkat lain', 'Jika akun ini sudah memiliki memo tersimpan, memo tersebut akan menggantikan pratinjau ini. Lanjutkan?', 'Buang perubahan yang belum disimpan dan muat versi server?']),
};
