import type { Lang } from '@/app/languages';

// Phrase order matches the English templates. Length and coverage are tested.
export const exampleCopy: Record<Lang, { brainstorm: string[]; groceries: string[]; meeting: string[]; todo: string[] }> = {
  en: {
    brainstorm: ['(example) Q3 Project Brainstorming', 'Project Goals', 'Focus on improving', 'user engagement', 'and', 'retention', 'Key Features', 'Gamification', '- Points, badges, streaks', 'Community Forums', '- User discussions', 'Personalized Recommendations', '- AI-driven suggestions', 'Data Structure Draft', 'Timeline', 'Phase', 'Duration', 'Status', 'Research', '2 weeks', '✅ Done', 'Design', '3 weeks', '🔄 In Progress', 'Development', '6 weeks', '⏳ Pending', 'Ship fast, iterate faster!'],
    groceries: ['(example) Weekly Grocery List', '🥛 Dairy', 'Milk (2L)', 'Greek Yogurt', 'Cheddar Cheese', '🍞 Bakery', 'Whole Wheat Bread', 'Croissants (4 pack)', '🍎 Produce', 'Apples', 'Bananas', 'Spinach', 'Budget Planner', 'Category', 'Est. Cost', 'Dairy', 'Bakery', 'Produce', 'Total'],
    meeting: ['(example) Design Team Meeting', 'Meeting Notes - Jan 15', 'Attendees:', 'Agenda', 'Review Q4 metrics', 'Discuss new color system', 'Plan user testing sessions', 'Deployment Plan', 'Action Items', 'Alex: Prepare color palette documentation', 'Jamie: Draft user testing script', 'Sam: Update Figma components', 'Next meeting: Jan 22, 10:00 AM'],
    todo: ['Submit project proposal', 'Review team feedback', 'Schedule client meeting', 'Buy groceries'],
  },
  ja: {
    brainstorm: ['(サンプル) 第3四半期のプロジェクト構想', 'プロジェクトの目標', '改善に注力する項目：', 'ユーザーの利用促進', 'と', '継続利用', '主な機能', 'ゲーム要素の導入', '- ポイント・バッジ・継続記録', 'コミュニティフォーラム', '- ユーザー同士の意見交換', '個別のおすすめ', '- AIによる提案', 'データ構造の下書き', 'スケジュール', '工程', '期間', '状態', '調査', '2週間', '✅ 完了', 'デザイン', '3週間', '🔄 進行中', '開発', '6週間', '⏳ 未着手', '早く形にして、さらに早く改善！'],
    groceries: ['(サンプル) 1週間の買い物リスト', '🥛 乳製品', '牛乳 (2L)', 'ギリシャヨーグルト', 'チェダーチーズ', '🍞 パン', '全粒粉パン', 'クロワッサン (4個入り)', '🍎 野菜・果物', 'りんご', 'バナナ', 'ほうれん草', '予算表', '分類', '予算の目安', '乳製品', 'パン', '野菜・果物', '合計'],
    meeting: ['(サンプル) デザインチームのミーティング', 'ミーティングメモ - 1月15日', '参加者：', '議題', '第4四半期の指標を確認', '新しいカラー体系について話し合う', 'ユーザーテストの日程を計画', 'デプロイ計画', '次のアクション', 'Alex：カラーパレットの資料を準備', 'Jamie：ユーザーテストの進行台本を作成', 'Sam：Figmaコンポーネントを更新', '次回：1月22日 午前10時'],
    todo: ['プロジェクト提案書を提出する', 'チームのフィードバックを確認する', 'クライアントとの打ち合わせを設定する', '食料品を買う'],
  },
  'zh-CN': {
    brainstorm: ['(示例) 第三季度项目头脑风暴', '项目目标', '重点提升', '用户参与度', '和', '留存率', '主要功能', '游戏化设计', '- 积分、徽章、连续记录', '社区论坛', '- 用户交流', '个性化推荐', '- AI驱动的建议', '数据结构草案', '时间安排', '阶段', '时长', '状态', '调研', '2周', '✅ 已完成', '设计', '3周', '🔄 进行中', '开发', '6周', '⏳ 待开始', '快速交付，更快迭代！'],
    groceries: ['(示例) 每周购物清单', '🥛 乳制品', '牛奶 (2L)', '希腊酸奶', '切达奶酪', '🍞 烘焙食品', '全麦面包', '牛角包 (4个装)', '🍎 蔬菜水果', '苹果', '香蕉', '菠菜', '预算表', '类别', '预计费用', '乳制品', '烘焙食品', '蔬菜水果', '合计'],
    meeting: ['(示例) 设计团队会议', '会议记录 - 1月15日', '参会者：', '议程', '回顾第四季度指标', '讨论新的配色体系', '安排用户测试', '部署计划', '待办事项', 'Alex：准备调色板文档', 'Jamie：起草用户测试脚本', 'Sam：更新Figma组件', '下次会议：1月22日 上午10点'],
    todo: ['提交项目提案', '查看团队反馈', '安排客户会议', '购买食材'],
  },
  ko: {
    brainstorm: ['(예시) 3분기 프로젝트 아이디어 회의', '프로젝트 목표', '개선할 항목:', '사용자 참여도', '및', '사용자 유지율', '주요 기능', '게임 요소 도입', '- 포인트, 배지, 연속 활동 기록', '커뮤니티 포럼', '- 사용자 간 토론', '맞춤 추천', '- AI 기반 제안', '데이터 구조 초안', '일정', '단계', '기간', '상태', '조사', '2주', '✅ 완료', '디자인', '3주', '🔄 진행 중', '개발', '6주', '⏳ 대기 중', '빠르게 출시하고, 더 빠르게 개선하세요!'],
    groceries: ['(예시) 주간 장보기 목록', '🥛 유제품', '우유 (2L)', '그릭 요거트', '체더 치즈', '🍞 빵류', '통밀빵', '크루아상 (4개입)', '🍎 채소와 과일', '사과', '바나나', '시금치', '예산표', '분류', '예상 비용', '유제품', '빵류', '채소와 과일', '합계'],
    meeting: ['(예시) 디자인팀 회의', '회의 메모 - 1월 15일', '참석자:', '안건', '4분기 지표 검토', '새로운 색상 체계 논의', '사용자 테스트 일정 계획', '배포 계획', '실행 항목', 'Alex: 색상 팔레트 문서 준비', 'Jamie: 사용자 테스트 진행안 작성', 'Sam: Figma 컴포넌트 업데이트', '다음 회의: 1월 22일 오전 10시'],
    todo: ['프로젝트 제안서 제출', '팀 피드백 검토', '고객 미팅 일정 잡기', '장보기'],
  },
  hi: {
    brainstorm: ['(उदाहरण) तीसरी तिमाही के प्रोजेक्ट पर विचार-मंथन', 'प्रोजेक्ट के लक्ष्य', 'इनमें सुधार पर ध्यान दें:', 'उपयोगकर्ता सहभागिता', 'और', 'उपयोगकर्ताओं को बनाए रखना', 'मुख्य सुविधाएँ', 'गेम जैसे तत्व', '- अंक, बैज, लगातार सक्रिय दिनों का रिकॉर्ड', 'सामुदायिक मंच', '- उपयोगकर्ताओं के बीच चर्चा', 'व्यक्तिगत सुझाव', '- AI पर आधारित सुझाव', 'डेटा संरचना का मसौदा', 'समयरेखा', 'चरण', 'अवधि', 'स्थिति', 'शोध', '2 सप्ताह', '✅ पूरा', 'डिज़ाइन', '3 सप्ताह', '🔄 जारी', 'विकास', '6 सप्ताह', '⏳ शुरू होना बाकी', 'जल्दी जारी करें, और भी जल्दी सुधारें!'],
    groceries: ['(उदाहरण) साप्ताहिक किराने की सूची', '🥛 डेयरी उत्पाद', 'दूध (2L)', 'ग्रीक योगर्ट', 'चेडर चीज़', '🍞 बेकरी उत्पाद', 'साबुत गेहूँ की ब्रेड', 'क्रोइसां (4 का पैक)', '🍎 फल और सब्ज़ियाँ', 'सेब', 'केले', 'पालक', 'बजट योजना', 'श्रेणी', 'अनुमानित लागत', 'डेयरी उत्पाद', 'बेकरी उत्पाद', 'फल और सब्ज़ियाँ', 'कुल'],
    meeting: ['(उदाहरण) डिज़ाइन टीम की बैठक', 'बैठक के नोट्स - 15 जनवरी', 'प्रतिभागी:', 'कार्यसूची', 'चौथी तिमाही के आँकड़ों की समीक्षा', 'नई रंग प्रणाली पर चर्चा', 'उपयोगकर्ता परीक्षण सत्रों की योजना', 'डिप्लॉयमेंट योजना', 'अगले कार्य', 'Alex: रंग पैलेट का दस्तावेज़ तैयार करें', 'Jamie: उपयोगकर्ता परीक्षण की रूपरेखा बनाएँ', 'Sam: Figma कंपोनेंट अपडेट करें', 'अगली बैठक: 22 जनवरी, सुबह 10:00 बजे'],
    todo: ['प्रोजेक्ट का प्रस्ताव जमा करें', 'टीम की प्रतिक्रिया की समीक्षा करें', 'क्लाइंट के साथ बैठक तय करें', 'किराने का सामान खरीदें'],
  },
  ar: {
    brainstorm: ['(مثال) عصف ذهني لمشروع الربع الثالث', 'أهداف المشروع', 'التركيز على تحسين', 'تفاعل المستخدمين', 'و', 'الاحتفاظ بالمستخدمين', 'الميزات الرئيسية', 'عناصر التلعيب', '- النقاط والشارات وسلاسل الاستمرارية', 'منتديات المجتمع', '- نقاشات المستخدمين', 'توصيات مخصصة', '- اقتراحات مدعومة بالذكاء الاصطناعي', 'مسودة بنية البيانات', 'الجدول الزمني', 'المرحلة', 'المدة', 'الحالة', 'البحث', 'أسبوعان', '✅ مكتمل', 'التصميم', '3 أسابيع', '🔄 قيد التنفيذ', 'التطوير', '6 أسابيع', '⏳ لم يبدأ', 'أطلق بسرعة، وحسّن بوتيرة أسرع!'],
    groceries: ['(مثال) قائمة المشتريات الأسبوعية', '🥛 منتجات الألبان', 'حليب (2L)', 'زبادي يوناني', 'جبن شيدر', '🍞 المخبوزات', 'خبز القمح الكامل', 'كرواسون (عبوة من 4 قطع)', '🍎 الخضروات والفواكه', 'تفاح', 'موز', 'سبانخ', 'خطة الميزانية', 'الفئة', 'التكلفة التقديرية', 'منتجات الألبان', 'المخبوزات', 'الخضروات والفواكه', 'الإجمالي'],
    meeting: ['(مثال) اجتماع فريق التصميم', 'ملاحظات الاجتماع - 15 يناير', 'المشاركون:', 'جدول الأعمال', 'مراجعة مؤشرات الربع الرابع', 'مناقشة نظام الألوان الجديد', 'تخطيط جلسات اختبار المستخدمين', 'خطة النشر', 'المهام المطلوبة', 'Alex: إعداد توثيق لوحة الألوان', 'Jamie: إعداد مسودة سيناريو اختبار المستخدمين', 'Sam: تحديث مكونات Figma', 'الاجتماع القادم: 22 يناير، الساعة 10:00 صباحًا'],
    todo: ['تقديم مقترح المشروع', 'مراجعة ملاحظات الفريق', 'تحديد موعد اجتماع مع العميل', 'شراء البقالة'],
  },
  ru: {
    brainstorm: ['(пример) Мозговой штурм по проекту на III квартал', 'Цели проекта', 'Сосредоточиться на улучшении следующих показателей:', 'вовлечённость пользователей', 'и', 'удержание пользователей', 'Основные функции', 'Геймификация', '- Баллы, значки, серии активности', 'Форумы сообщества', '- Обсуждения пользователей', 'Персональные рекомендации', '- Предложения на основе ИИ', 'Черновик структуры данных', 'График', 'Этап', 'Продолжительность', 'Статус', 'Исследование', '2 недели', '✅ Готово', 'Дизайн', '3 недели', '🔄 В работе', 'Разработка', '6 недель', '⏳ Ожидает начала', 'Выпускайте быстро, улучшайте ещё быстрее!'],
    groceries: ['(пример) Список покупок на неделю', '🥛 Молочные продукты', 'Молоко (2L)', 'Греческий йогурт', 'Сыр чеддер', '🍞 Выпечка', 'Цельнозерновой хлеб', 'Круассаны (4 шт.)', '🍎 Овощи и фрукты', 'Яблоки', 'Бананы', 'Шпинат', 'План бюджета', 'Категория', 'Ожидаемые расходы', 'Молочные продукты', 'Выпечка', 'Овощи и фрукты', 'Итого'],
    meeting: ['(пример) Встреча команды дизайна', 'Заметки со встречи — 15 января', 'Участники:', 'Повестка', 'Обзор показателей IV квартала', 'Обсуждение новой цветовой системы', 'Планирование пользовательских тестов', 'План развёртывания', 'Задачи по итогам', 'Alex: подготовить документацию по цветовой палитре', 'Jamie: составить сценарий пользовательского тестирования', 'Sam: обновить компоненты Figma', 'Следующая встреча: 22 января, 10:00'],
    todo: ['Отправить предложение по проекту', 'Изучить отзывы команды', 'Назначить встречу с клиентом', 'Купить продукты'],
  },
  id: {
    brainstorm: ['(contoh) Curah Ide Proyek Kuartal 3', 'Tujuan Proyek', 'Fokus pada peningkatan', 'keterlibatan pengguna', 'dan', 'retensi pengguna', 'Fitur Utama', 'Gamifikasi', '- Poin, lencana, rangkaian aktivitas', 'Forum Komunitas', '- Diskusi pengguna', 'Rekomendasi Personal', '- Saran berbasis AI', 'Draf Struktur Data', 'Jadwal', 'Tahap', 'Durasi', 'Status', 'Riset', '2 minggu', '✅ Selesai', 'Desain', '3 minggu', '🔄 Sedang Berjalan', 'Pengembangan', '6 minggu', '⏳ Belum Dimulai', 'Rilis cepat, perbaiki lebih cepat!'],
    groceries: ['(contoh) Daftar Belanja Mingguan', '🥛 Produk Susu', 'Susu (2L)', 'Yoghurt Yunani', 'Keju Cheddar', '🍞 Roti dan Kue', 'Roti Gandum Utuh', 'Kroisan (isi 4)', '🍎 Buah dan Sayur', 'Apel', 'Pisang', 'Bayam', 'Rencana Anggaran', 'Kategori', 'Perkiraan Biaya', 'Produk Susu', 'Roti dan Kue', 'Buah dan Sayur', 'Total'],
    meeting: ['(contoh) Rapat Tim Desain', 'Catatan Rapat - 15 Januari', 'Peserta:', 'Agenda', 'Tinjau metrik kuartal 4', 'Diskusikan sistem warna baru', 'Rencanakan sesi pengujian pengguna', 'Rencana Deployment', 'Tindak Lanjut', 'Alex: Siapkan dokumentasi palet warna', 'Jamie: Susun draf skenario pengujian pengguna', 'Sam: Perbarui komponen Figma', 'Rapat berikutnya: 22 Januari, pukul 10.00 pagi'],
    todo: ['Kirim proposal proyek', 'Tinjau masukan tim', 'Jadwalkan rapat dengan klien', 'Belanja bahan makanan'],
  },
  es: {
    brainstorm: ['(ejemplo) Lluvia de ideas del proyecto del tercer trimestre', 'Objetivos del proyecto', 'Centrarse en mejorar', 'la participación de los usuarios', 'y', 'su retención', 'Funciones principales', 'Gamificación', '- Puntos, insignias, rachas', 'Foros de la comunidad', '- Conversaciones entre usuarios', 'Recomendaciones personalizadas', '- Sugerencias basadas en IA', 'Borrador de la estructura de datos', 'Cronograma', 'Fase', 'Duración', 'Estado', 'Investigación', '2 semanas', '✅ Hecho', 'Diseño', '3 semanas', '🔄 En curso', 'Desarrollo', '6 semanas', '⏳ Pendiente', '¡Publica rápido y mejora aún más rápido!'],
    groceries: ['(ejemplo) Lista de la compra semanal', '🥛 Lácteos', 'Leche (2L)', 'Yogur griego', 'Queso cheddar', '🍞 Panadería', 'Pan integral', 'Cruasanes (paquete de 4)', '🍎 Frutas y verduras', 'Manzanas', 'Plátanos', 'Espinacas', 'Plan de presupuesto', 'Categoría', 'Coste estimado', 'Lácteos', 'Panadería', 'Frutas y verduras', 'Total'],
    meeting: ['(ejemplo) Reunión del equipo de diseño', 'Notas de la reunión - 15 de enero', 'Asistentes:', 'Orden del día', 'Revisar las métricas del cuarto trimestre', 'Debatir el nuevo sistema de colores', 'Planificar sesiones de pruebas con usuarios', 'Plan de despliegue', 'Tareas pendientes', 'Alex: Preparar la documentación de la paleta de colores', 'Jamie: Redactar el guion de las pruebas con usuarios', 'Sam: Actualizar los componentes de Figma', 'Próxima reunión: 22 de enero, 10:00 a. m.'],
    todo: ['Enviar la propuesta del proyecto', 'Revisar los comentarios del equipo', 'Programar una reunión con el cliente', 'Comprar alimentos'],
  },
  fr: {
    brainstorm: ['(exemple) Remue-méninges sur le projet du troisième trimestre', 'Objectifs du projet', 'Se concentrer sur l’amélioration de', 'l’engagement des utilisateurs', 'et de', 'leur fidélisation', 'Fonctions principales', 'Ludification', '- Points, badges, séries d’activité', 'Forums communautaires', '- Discussions entre utilisateurs', 'Recommandations personnalisées', '- Suggestions fondées sur l’IA', 'Ébauche de la structure des données', 'Calendrier', 'Phase', 'Durée', 'État', 'Recherche', '2 semaines', '✅ Terminé', 'Conception', '3 semaines', '🔄 En cours', 'Développement', '6 semaines', '⏳ En attente', 'Publiez vite, améliorez encore plus vite !'],
    groceries: ['(exemple) Liste de courses de la semaine', '🥛 Produits laitiers', 'Lait (2L)', 'Yaourt grec', 'Cheddar', '🍞 Boulangerie', 'Pain complet', 'Croissants (lot de 4)', '🍎 Fruits et légumes', 'Pommes', 'Bananes', 'Épinards', 'Prévision budgétaire', 'Catégorie', 'Coût estimé', 'Produits laitiers', 'Boulangerie', 'Fruits et légumes', 'Total'],
    meeting: ['(exemple) Réunion de l’équipe de conception', 'Notes de réunion - 15 janvier', 'Participants :', 'Ordre du jour', 'Examiner les indicateurs du quatrième trimestre', 'Discuter du nouveau système de couleurs', 'Planifier les tests utilisateurs', 'Plan de déploiement', 'Actions à mener', 'Alex : préparer la documentation de la palette de couleurs', 'Jamie : rédiger le scénario des tests utilisateurs', 'Sam : mettre à jour les composants Figma', 'Prochaine réunion : le 22 janvier à 10 h'],
    todo: ['Envoyer la proposition de projet', 'Examiner les retours de l’équipe', 'Planifier une réunion avec le client', 'Faire les courses'],
  },
  'pt-BR': {
    brainstorm: ['(exemplo) Brainstorming do projeto do terceiro trimestre', 'Objetivos do projeto', 'Focar na melhoria do', 'engajamento dos usuários', 'e da', 'retenção', 'Principais recursos', 'Gamificação', '- Pontos, emblemas, sequências de atividade', 'Fóruns da comunidade', '- Discussões entre usuários', 'Recomendações personalizadas', '- Sugestões baseadas em IA', 'Rascunho da estrutura de dados', 'Cronograma', 'Fase', 'Duração', 'Status', 'Pesquisa', '2 semanas', '✅ Concluído', 'Design', '3 semanas', '🔄 Em andamento', 'Desenvolvimento', '6 semanas', '⏳ Pendente', 'Lance rápido e melhore ainda mais rápido!'],
    groceries: ['(exemplo) Lista de compras da semana', '🥛 Laticínios', 'Leite (2L)', 'Iogurte grego', 'Queijo cheddar', '🍞 Padaria', 'Pão integral', 'Croissants (pacote com 4)', '🍎 Frutas e verduras', 'Maçãs', 'Bananas', 'Espinafre', 'Planejamento do orçamento', 'Categoria', 'Custo estimado', 'Laticínios', 'Padaria', 'Frutas e verduras', 'Total'],
    meeting: ['(exemplo) Reunião da equipe de design', 'Notas da reunião - 15 de janeiro', 'Participantes:', 'Pauta', 'Revisar os indicadores do quarto trimestre', 'Discutir o novo sistema de cores', 'Planejar sessões de testes com usuários', 'Plano de implantação', 'Próximas ações', 'Alex: Preparar a documentação da paleta de cores', 'Jamie: Elaborar o roteiro dos testes com usuários', 'Sam: Atualizar os componentes do Figma', 'Próxima reunião: 22 de janeiro, às 10h'],
    todo: ['Enviar a proposta do projeto', 'Revisar o feedback da equipe', 'Agendar uma reunião com o cliente', 'Comprar alimentos'],
  },
};
