import type { Lang } from '@/app/languages';

type Words = [
  section: string, open: string, openDescription: string, title: string, description: string, chooseFolder: string, chooseFiles: string,
  reading: string, summary: string, embeds: string, skipped: string, tooLarge: string, unsupported: string, invalid: string,
  nothing: string, limitNotes: string, limitGroups: string, limitSize: string, confirm: string, cancel: string, saving: string,
  failed: string, retry: string, done: string, close: string, showTray: string, image: string, file: string,
];
const copy = ([section, open, openDescription, title, description, chooseFolder, chooseFiles, reading, summary, embeds, skipped, tooLarge, unsupported, invalid,
  nothing, limitNotes, limitGroups, limitSize, confirm, cancel, saving, failed, retry, done, close, showTray, image, file]: Words) => ({
  section, open, openDescription, title, description, chooseFolder, chooseFiles, reading, summary, embeds, skipped,
  reasons: { tooLarge, unsupported, invalid }, nothing, limits: { notes: limitNotes, groups: limitGroups, size: limitSize },
  confirm, cancel, saving, failed, retry, done, close, showTray, image, file,
});

// Placeholders: {trays} {memos} {count} {done} {total} {saved} {unsaved}
export const importCopy: Record<Lang, ReturnType<typeof copy>> = {
  en: copy(['Data', 'Import', 'Import memos from an Obsidian vault. Existing trays and memos are not changed.', 'Import from Obsidian',
    'Choose your vault folder or .md files. Files are read and converted on this device and nothing is saved until you confirm.', 'Choose folder', 'Choose files',
    'Reading files…', 'Creates {memos} memos in {trays} new trays.', '{count} images or embeds are not imported. Their names stay in the text.', 'Files not imported ({count})',
    'Too large', 'Unsupported format', 'Could not convert', 'No Markdown files to import.', 'This would exceed the limit of 10,000 memos.', 'This would exceed the limit of 1,000 trays.',
    'This would exceed the total storage limit.', 'Import', 'Cancel', 'Saving… {done} / {total}', 'Saving stopped. Saved: {saved}. Not saved: {unsaved}.', 'Retry unsaved memos',
    'Imported {memos} memos.', 'Close', 'Open imported tray', 'Image', 'File']),
  ja: copy(['データ', 'インポート', 'ObsidianのVaultからメモを取り込みます. 既存のトレイ・メモは変更しません.', 'Obsidianから取り込む',
    'Vaultのフォルダ, または.mdファイルを選んでください. 読み込みと変換はこの端末内で行い, 確定するまで保存しません.', 'フォルダを選択', 'ファイルを選択',
    '読み込み中…', '新しいトレイ {trays}個に, メモ {memos}件を作成します.', '画像・埋め込み{count}件は取り込まず, 本文に名前を残します.', '取り込めないファイル ({count})',
    '大きすぎます', '非対応の形式です', '変換できません', '取り込めるMarkdownファイルがありません.', 'メモの上限 (1万件) を超えるため取り込めません.', 'トレイの上限 (1000個) を超えるため取り込めません.',
    '全体の保存容量の上限を超えるため取り込めません.', '取り込む', 'キャンセル', '保存中… {done} / {total}', '保存が止まりました. 保存済み {saved}件, 未保存 {unsaved}件です.', '未保存分を再試行',
    'メモ {memos}件を取り込みました.', '閉じる', '取り込んだトレイを開く', '画像', '添付']),
  'zh-CN': copy(['数据', '导入', '从 Obsidian 仓库导入备忘录。不会更改现有的托盘和备忘录。', '从 Obsidian 导入',
    '请选择仓库文件夹或 .md 文件。文件在本设备上读取和转换，确认前不会保存。', '选择文件夹', '选择文件',
    '正在读取文件…', '将在 {trays} 个新托盘中创建 {memos} 条备忘录。', '{count} 个图片或嵌入内容不会导入，名称保留在正文中。', '未导入的文件（{count}）',
    '文件过大', '不支持的格式', '无法转换', '没有可导入的 Markdown 文件。', '将超过 10,000 条备忘录的上限。', '将超过 1,000 个托盘的上限。',
    '将超过总存储容量上限。', '导入', '取消', '正在保存… {done} / {total}', '保存已停止。已保存：{saved}。未保存：{unsaved}。', '重试未保存的备忘录',
    '已导入 {memos} 条备忘录。', '关闭', '打开导入的托盘', '图片', '附件']),
  ko: copy(['데이터', '가져오기', 'Obsidian 보관소에서 메모를 가져옵니다. 기존 트레이와 메모는 변경하지 않습니다.', 'Obsidian에서 가져오기',
    '보관소 폴더나 .md 파일을 선택하세요. 파일은 이 기기에서 읽고 변환하며, 확정하기 전에는 저장하지 않습니다.', '폴더 선택', '파일 선택',
    '파일을 읽는 중…', '새 트레이 {trays}개에 메모 {memos}개를 만듭니다.', '이미지·삽입 {count}개는 가져오지 않고 본문에 이름을 남깁니다.', '가져오지 못한 파일 ({count})',
    '너무 큽니다', '지원하지 않는 형식입니다', '변환할 수 없습니다', '가져올 Markdown 파일이 없습니다.', '메모 한도(10,000개)를 넘어 가져올 수 없습니다.', '트레이 한도(1,000개)를 넘어 가져올 수 없습니다.',
    '전체 저장 용량 한도를 넘어 가져올 수 없습니다.', '가져오기', '취소', '저장 중… {done} / {total}', '저장이 멈췄습니다. 저장됨: {saved}개, 저장 안 됨: {unsaved}개.', '저장 안 된 메모 다시 시도',
    '메모 {memos}개를 가져왔습니다.', '닫기', '가져온 트레이 열기', '이미지', '첨부']),
  es: copy(['Datos', 'Importar', 'Importa notas desde una bóveda de Obsidian. Las bandejas y notas existentes no cambian.', 'Importar desde Obsidian',
    'Elige la carpeta de la bóveda o archivos .md. Se leen y convierten en este dispositivo y no se guarda nada hasta que confirmes.', 'Elegir carpeta', 'Elegir archivos',
    'Leyendo archivos…', 'Crea {memos} notas en {trays} bandejas nuevas.', '{count} imágenes o incrustaciones no se importan. Sus nombres quedan en el texto.', 'Archivos no importados ({count})',
    'Demasiado grande', 'Formato no compatible', 'No se pudo convertir', 'No hay archivos Markdown para importar.', 'Se superaría el límite de 10.000 notas.', 'Se superaría el límite de 1.000 bandejas.',
    'Se superaría el límite total de almacenamiento.', 'Importar', 'Cancelar', 'Guardando… {done} / {total}', 'El guardado se detuvo. Guardadas: {saved}. Sin guardar: {unsaved}.', 'Reintentar las no guardadas',
    'Se importaron {memos} notas.', 'Cerrar', 'Abrir la bandeja importada', 'Imagen', 'Archivo']),
  fr: copy(['Données', 'Importer', 'Importe des notes depuis un coffre Obsidian. Les bacs et notes existants ne sont pas modifiés.', 'Importer depuis Obsidian',
    'Choisissez le dossier du coffre ou des fichiers .md. Ils sont lus et convertis sur cet appareil et rien n’est enregistré avant votre confirmation.', 'Choisir un dossier', 'Choisir des fichiers',
    'Lecture des fichiers…', 'Crée {memos} notes dans {trays} nouveaux bacs.', '{count} images ou intégrations ne sont pas importées. Leurs noms restent dans le texte.', 'Fichiers non importés ({count})',
    'Trop volumineux', 'Format non pris en charge', 'Conversion impossible', 'Aucun fichier Markdown à importer.', 'La limite de 10 000 notes serait dépassée.', 'La limite de 1 000 bacs serait dépassée.',
    'La limite totale de stockage serait dépassée.', 'Importer', 'Annuler', 'Enregistrement… {done} / {total}', 'L’enregistrement s’est arrêté. Enregistrées : {saved}. Non enregistrées : {unsaved}.', 'Réessayer les notes non enregistrées',
    '{memos} notes importées.', 'Fermer', 'Ouvrir le bac importé', 'Image', 'Fichier']),
  'pt-BR': copy(['Dados', 'Importar', 'Importa notas de um cofre do Obsidian. Bandejas e notas existentes não são alteradas.', 'Importar do Obsidian',
    'Escolha a pasta do cofre ou arquivos .md. Eles são lidos e convertidos neste dispositivo e nada é salvo até você confirmar.', 'Escolher pasta', 'Escolher arquivos',
    'Lendo arquivos…', 'Cria {memos} notas em {trays} novas bandejas.', '{count} imagens ou incorporações não são importadas. Os nomes ficam no texto.', 'Arquivos não importados ({count})',
    'Grande demais', 'Formato não suportado', 'Não foi possível converter', 'Não há arquivos Markdown para importar.', 'Isso excederia o limite de 10.000 notas.', 'Isso excederia o limite de 1.000 bandejas.',
    'Isso excederia o limite total de armazenamento.', 'Importar', 'Cancelar', 'Salvando… {done} / {total}', 'O salvamento parou. Salvas: {saved}. Não salvas: {unsaved}.', 'Tentar salvar as restantes',
    '{memos} notas importadas.', 'Fechar', 'Abrir a bandeja importada', 'Imagem', 'Arquivo']),
  hi: copy(['डेटा', 'आयात करें', 'Obsidian वॉल्ट से नोट आयात करें। मौजूदा ट्रे और नोट नहीं बदलते।', 'Obsidian से आयात करें',
    'वॉल्ट फ़ोल्डर या .md फ़ाइलें चुनें। फ़ाइलें इसी डिवाइस पर पढ़ी और बदली जाती हैं, और पुष्टि से पहले कुछ भी सहेजा नहीं जाता।', 'फ़ोल्डर चुनें', 'फ़ाइलें चुनें',
    'फ़ाइलें पढ़ी जा रही हैं…', '{trays} नई ट्रे में {memos} नोट बनाए जाएँगे।', '{count} चित्र या एम्बेड आयात नहीं होंगे। उनके नाम पाठ में रहेंगे।', 'आयात न हुई फ़ाइलें ({count})',
    'बहुत बड़ी', 'असमर्थित प्रारूप', 'बदला नहीं जा सका', 'आयात के लिए कोई Markdown फ़ाइल नहीं है।', '10,000 नोट की सीमा पार हो जाएगी।', '1,000 ट्रे की सीमा पार हो जाएगी।',
    'कुल संग्रहण सीमा पार हो जाएगी।', 'आयात करें', 'रद्द करें', 'सहेजा जा रहा है… {done} / {total}', 'सहेजना रुक गया। सहेजे गए: {saved}। नहीं सहेजे गए: {unsaved}।', 'न सहेजे गए नोट फिर से आज़माएँ',
    '{memos} नोट आयात किए गए।', 'बंद करें', 'आयात की गई ट्रे खोलें', 'चित्र', 'फ़ाइल']),
  ar: copy(['البيانات', 'استيراد', 'استيراد الملاحظات من خزنة Obsidian. لا تتغير الأدراج والملاحظات الحالية.', 'الاستيراد من Obsidian',
    'اختر مجلد الخزنة أو ملفات .md. تُقرأ الملفات وتُحوَّل على هذا الجهاز، ولا يُحفظ شيء قبل تأكيدك.', 'اختيار مجلد', 'اختيار ملفات',
    'جارٍ قراءة الملفات…', 'سيُنشئ {memos} ملاحظة في {trays} أدراج جديدة.', 'لن تُستورد {count} من الصور أو العناصر المضمّنة، وتبقى أسماؤها في النص.', 'ملفات لم تُستورد ({count})',
    'كبير جدًا', 'تنسيق غير مدعوم', 'تعذّر التحويل', 'لا توجد ملفات Markdown للاستيراد.', 'سيتجاوز ذلك حد 10,000 ملاحظة.', 'سيتجاوز ذلك حد 1,000 درج.',
    'سيتجاوز ذلك حد التخزين الإجمالي.', 'استيراد', 'إلغاء', 'جارٍ الحفظ… {done} / {total}', 'توقف الحفظ. المحفوظة: {saved}. غير المحفوظة: {unsaved}.', 'إعادة محاولة غير المحفوظة',
    'تم استيراد {memos} ملاحظة.', 'إغلاق', 'فتح الدرج المستوردة', 'صورة', 'ملف']),
  ru: copy(['Данные', 'Импорт', 'Импорт заметок из хранилища Obsidian. Существующие лотки и заметки не меняются.', 'Импорт из Obsidian',
    'Выберите папку хранилища или файлы .md. Файлы читаются и преобразуются на этом устройстве, и ничего не сохраняется до подтверждения.', 'Выбрать папку', 'Выбрать файлы',
    'Чтение файлов…', 'Будет создано заметок: {memos} в новых лотках: {trays}.', 'Изображения и вставки ({count}) не импортируются. Их названия остаются в тексте.', 'Не импортированные файлы ({count})',
    'Слишком большой', 'Неподдерживаемый формат', 'Не удалось преобразовать', 'Нет файлов Markdown для импорта.', 'Будет превышен лимит в 10 000 заметок.', 'Будет превышен лимит в 1 000 лотков.',
    'Будет превышен общий лимит хранилища.', 'Импортировать', 'Отмена', 'Сохранение… {done} / {total}', 'Сохранение остановлено. Сохранено: {saved}. Не сохранено: {unsaved}.', 'Повторить для несохранённых',
    'Импортировано заметок: {memos}.', 'Закрыть', 'Открыть импортированный лоток', 'Изображение', 'Файл']),
  id: copy(['Data', 'Impor', 'Impor catatan dari vault Obsidian. Nampan dan catatan yang ada tidak diubah.', 'Impor dari Obsidian',
    'Pilih folder vault atau file .md. File dibaca dan dikonversi di perangkat ini, dan tidak ada yang disimpan sebelum Anda mengonfirmasi.', 'Pilih folder', 'Pilih file',
    'Membaca file…', 'Membuat {catatans} catatan di {trays} nampan baru.', '{count} gambar atau sematan tidak diimpor. Namanya tetap ada di teks.', 'File yang tidak diimpor ({count})',
    'Terlalu besar', 'Format tidak didukung', 'Tidak dapat dikonversi', 'Tidak ada file Markdown untuk diimpor.', 'Akan melebihi batas 10.000 catatan.', 'Akan melebihi batas 1.000 nampan.',
    'Akan melebihi batas total penyimpanan.', 'Impor', 'Batal', 'Menyimpan… {done} / {total}', 'Penyimpanan berhenti. Tersimpan: {saved}. Belum tersimpan: {unsaved}.', 'Coba lagi yang belum tersimpan',
    '{catatans} catatan diimpor.', 'Tutup', 'Buka nampan yang diimpor', 'Gambar', 'File']),
};

export const fillCopy = (text: string, values: Record<string, number | string>) => text.replace(/\{(\w+)\}/g, (match, key: string) => key in values ? String(values[key]) : match);
