import type { Lang } from '@/app/languages';
export const memoHistoryCloseCopy: Record<Lang, string> = { en: 'Close', ja: '閉じる', 'zh-CN': '关闭', ko: '닫기', es: 'Cerrar', fr: 'Fermer', 'pt-BR': 'Fechar', hi: 'बंद करें', ar: 'إغلاق', ru: 'Закрыть', id: 'Tutup' };
type Words = [title: string, description: string, empty: string, loading: string, failed: string, retry: string, refresh: string, restore: string, restoring: string, restored: string, suffix: string, tray: string, warning: string];
const copy = ([title, description, empty, loading, failed, retry, refresh, restore, restoring, restored, suffix, tray, warning]: Words) => ({ title, description, empty, loading, failed, retry, refresh, restore, restoring, restored, suffix, tray, warning });
export const memoHistoryCopy: Record<Lang, ReturnType<typeof copy>> = {
  en: copy(['Memo history', 'Keeps up to 20 earlier versions, normally at five-minute intervals. Restore a version as a separate memo.', 'No earlier versions yet. History starts when this memo is saved or edited.', 'Loading history…', 'Could not load or restore history.', 'Retry', 'Refresh history', 'Restore as a new memo', 'Restoring…', 'An earlier version was restored as a separate memo.', 'Restored', 'Restored memos', 'Your memo changes were saved, but history could not be recorded or cleaned up.']),
  ja: copy(['保存履歴', '編集前の版を通常5分間隔で20版まで残します. 選んだ版は別Memoへ復元します.', 'まだ保存履歴がありません. このMemoの保存・編集から記録を始めます.', '履歴を読み込み中…', '履歴の読み込み・復元に失敗しました.', '再試行', '履歴を更新', '別Memoとして復元', '復元中…', '過去の版を別Memoとして復元しました.', '復元', '復元したメモ', 'Memoの変更は保存済みですが, 履歴の記録・整理に失敗しました.']),
  'zh-CN': copy(['保存历史', '通常每五分钟保留一次编辑前的版本，最多20版。选中的版本将恢复为独立备忘录。', '暂无历史版本。保存或编辑此备忘录后开始记录。', '正在加载历史…', '无法加载或恢复历史。', '重试', '刷新历史', '恢复为新备忘录', '正在恢复…', '已将历史版本恢复为独立备忘录。', '已恢复', '恢复的备忘录', '备忘录更改已保存，但无法记录或清理历史。']),
  ko: copy(['저장 이력', '보통 5분 간격으로 편집 전 버전을 최대 20개 보관합니다. 선택한 버전은 별도 메모로 복원합니다.', '이전 버전이 없습니다. 이 메모를 저장하거나 편집하면 기록을 시작합니다.', '이력을 불러오는 중…', '이력을 불러오거나 복원하지 못했습니다.', '다시 시도', '이력 새로고침', '새 메모로 복원', '복원 중…', '이전 버전을 별도 메모로 복원했습니다.', '복원됨', '복원한 메모', '메모 변경은 저장했지만 이력 기록 또는 정리에 실패했습니다.']),
  es: copy(['Historial de la nota', 'Conserva hasta 20 versiones anteriores, normalmente cada cinco minutos. Restaura una versión como una nota independiente.', 'No hay versiones anteriores. El historial comienza al guardar o editar esta nota.', 'Cargando historial…', 'No se pudo cargar o restaurar el historial.', 'Reintentar', 'Actualizar historial', 'Restaurar como nota nueva', 'Restaurando…', 'Se restauró una versión anterior como una nota independiente.', 'Restaurada', 'Notas restauradas', 'Los cambios se guardaron, pero no se pudo registrar o limpiar el historial.']),
  fr: copy(['Historique de la note', 'Conserve jusqu’à 20 versions antérieures, normalement toutes les cinq minutes. Restaurez une version dans une note distincte.', 'Aucune version antérieure. L’historique commence à l’enregistrement ou à la modification de cette note.', 'Chargement de l’historique…', 'Impossible de charger ou de restaurer l’historique.', 'Réessayer', 'Actualiser l’historique', 'Restaurer dans une nouvelle note', 'Restauration…', 'Une version antérieure a été restaurée dans une note distincte.', 'Restaurée', 'Notes restaurées', 'Les modifications sont enregistrées, mais l’historique n’a pas pu être enregistré ou nettoyé.']),
  'pt-BR': copy(['Histórico da nota', 'Mantém até 20 versões anteriores, normalmente a cada cinco minutos. Restaure uma versão como uma nota separada.', 'Não há versões anteriores. O histórico começa ao salvar ou editar esta nota.', 'Carregando histórico…', 'Não foi possível carregar ou restaurar o histórico.', 'Tentar novamente', 'Atualizar histórico', 'Restaurar como nova nota', 'Restaurando…', 'Uma versão anterior foi restaurada como uma nota separada.', 'Restaurada', 'Notas restauradas', 'As alterações foram salvas, mas não foi possível registrar ou limpar o histórico.']),
  hi: copy(['मेमो इतिहास', 'आम तौर पर पाँच मिनट के अंतराल पर संपादन से पहले के अधिकतम 20 संस्करण रखता है। चुना संस्करण अलग मेमो के रूप में बहाल करें।', 'अभी पुराने संस्करण नहीं हैं। इस मेमो को सहेजने या संपादित करने पर इतिहास शुरू होता है।', 'इतिहास लोड हो रहा है…', 'इतिहास लोड या बहाल नहीं हो सका।', 'फिर कोशिश करें', 'इतिहास ताज़ा करें', 'नए मेमो के रूप में बहाल करें', 'बहाल हो रहा है…', 'पुराना संस्करण अलग मेमो के रूप में बहाल किया गया।', 'बहाल', 'बहाल मेमो', 'मेमो के बदलाव सहेजे गए, लेकिन इतिहास दर्ज या साफ़ नहीं हो सका।']),
  ar: copy(['سجل الملاحظة', 'يحتفظ بما يصل إلى 20 نسخة سابقة، عادة كل خمس دقائق. استعد النسخة المحددة كملاحظة منفصلة.', 'لا توجد نسخ سابقة بعد. يبدأ السجل عند حفظ هذه الملاحظة أو تعديلها.', 'جارٍ تحميل السجل…', 'تعذر تحميل السجل أو استعادته.', 'إعادة المحاولة', 'تحديث السجل', 'استعادة كملاحظة جديدة', 'جارٍ الاستعادة…', 'استُعيدت نسخة سابقة كملاحظة منفصلة.', 'مستعادة', 'ملاحظات مستعادة', 'حُفظت تغييرات الملاحظة، لكن تعذر تسجيل السجل أو تنظيفه.']),
  ru: copy(['История заметки', 'Хранит до 20 предыдущих версий, обычно с интервалом в пять минут. Выбранная версия восстанавливается в отдельную заметку.', 'Предыдущих версий пока нет. История появится при сохранении или редактировании заметки.', 'Загрузка истории…', 'Не удалось загрузить или восстановить историю.', 'Повторить', 'Обновить историю', 'Восстановить в новую заметку', 'Восстановление…', 'Предыдущая версия восстановлена в отдельную заметку.', 'Восстановлена', 'Восстановленные заметки', 'Изменения сохранены, но не удалось записать или очистить историю.']),
  id: copy(['Riwayat memo', 'Menyimpan hingga 20 versi sebelumnya, biasanya setiap lima menit. Pulihkan versi pilihan sebagai memo terpisah.', 'Belum ada versi sebelumnya. Riwayat dimulai saat memo ini disimpan atau diedit.', 'Memuat riwayat…', 'Tidak dapat memuat atau memulihkan riwayat.', 'Coba lagi', 'Segarkan riwayat', 'Pulihkan sebagai memo baru', 'Memulihkan…', 'Versi sebelumnya dipulihkan sebagai memo terpisah.', 'Dipulihkan', 'Memo yang dipulihkan', 'Perubahan memo tersimpan, tetapi riwayat tidak dapat dicatat atau dibersihkan.']),
};
