import type { Lang } from '@/app/languages';

type Copy = { release020: string; warning: string; nextBody: string; laterBody: string };
export const authRetryReleaseCopy: Record<Lang, string> = {
  en: 'Fixed sign-in retries after a blocked or closed popup. Retry now restarts Google sign-in without clearing guest memos. Sign-in confirmation now appears inside the app.',
  ja: 'ログイン用ポップアップがブロックされた場合などの再試行を修正しました. 未ログインのメモを残したままGoogle認証をやり直せます. ログイン前の確認も画面内へ移しました.',
  'zh-CN': '修复了登录弹窗被拦截或关闭后的重试。现在重试会重新启动Google登录，不会清除访客备忘录。登录确认改为在应用内显示。',
  ko: '로그인 팝업이 차단되거나 닫힌 후의 재시도를 수정했습니다. 이제 게스트 메모를 지우지 않고 Google 로그인을 다시 시작합니다. 로그인 확인도 앱 안에 표시합니다.',
  es: 'Corregimos el reintento tras bloquear o cerrar la ventana de acceso. Ahora reinicia el acceso con Google sin borrar las notas de invitado. La confirmación aparece dentro de la app.',
  fr: 'Correction de la nouvelle tentative après le blocage ou la fermeture de la fenêtre de connexion. Elle relance la connexion Google sans effacer les notes invitées. La confirmation s’affiche dans l’application.',
  'pt-BR': 'Corrigimos a nova tentativa após um pop-up de login ser bloqueado ou fechado. Ela reinicia o login Google sem apagar as notas de visitante. A confirmação agora aparece no aplicativo.',
  hi: 'लॉगिन पॉपअप ब्लॉक या बंद होने के बाद दोबारा कोशिश करने की समस्या ठीक की गई। अब अतिथि मेमो मिटाए बिना Google साइन-इन फिर शुरू होता है। पुष्टि ऐप के अंदर दिखाई देती है।',
  ar: 'أُصلحت إعادة المحاولة بعد حظر نافذة تسجيل الدخول أو إغلاقها. تبدأ الآن تسجيل الدخول باستخدام Google مجددًا دون مسح ملاحظات الضيف. يظهر التأكيد داخل التطبيق.',
  ru: 'Исправлен повторный вход после блокировки или закрытия всплывающего окна. Повтор запускает вход через Google, не удаляя гостевые заметки. Подтверждение теперь отображается в приложении.',
  id: 'Memperbaiki percobaan ulang setelah pop-up login diblokir atau ditutup. Kini login Google dimulai ulang tanpa menghapus memo tamu. Konfirmasi ditampilkan di dalam aplikasi.',
};
function copy(release020: string, warning: string, nextBody: string, laterBody: string): Copy {
  return { release020, warning, nextBody, laterBody };
}
export const persistenceReleaseCopy: Record<Lang, Copy> = {
  en: copy('Added Google sign-in and automatic cloud saving for memos, trays and settings. Restore your workspace after reloading or signing in again. Save failures can be retried, and conflicting changes are not overwritten automatically.', 'Sign in with Google to save. Guest memos are temporary. Wait for “Saved” before closing.', 'Improve cross-device sync and failure recovery.', 'Profiles, manual backup and restore, and a feedback form; an ad-free beta to validate everyday use.'),
  ja: copy('Googleログインと, Memo･Tray･設定の自動保存に対応しました. 再読み込みや再ログイン後も復元できます. 保存失敗時は再試行でき, 競合する変更は自動で上書きしません.', '保存にはGoogleログインが必要です. 未ログインのメモは一時的なものです. 閉じる前に「保存済み」を確認してください.', '端末間の同期と, 通信障害などからの復旧を強化します.', 'プロファイル, 手動バックアップ･復元, フィードバックフォームを用意し, 広告なしの無料βで実用性を検証します.'),
  'zh-CN': copy('新增Google登录以及备忘录、托盘和设置的云端自动保存。重新加载或再次登录后可恢复工作区。保存失败时可重试，冲突的更改不会被自动覆盖。', '请使用Google登录以保存数据。未登录的备忘录仅临时保留。关闭前请确认“已保存”。', '改进跨设备同步和故障恢复。', '提供配置档案、手动备份与恢复和反馈表单，并通过无广告免费测试版验证日常使用。'),
  ko: copy('Google 로그인과 메모, 트레이, 설정의 클라우드 자동 저장을 추가했습니다. 새로고침하거나 다시 로그인한 후 작업 공간을 복원할 수 있습니다. 저장 실패 시 다시 시도할 수 있으며 충돌하는 변경 사항은 자동으로 덮어쓰지 않습니다.', '저장하려면 Google로 로그인하세요. 로그인하지 않은 메모는 임시로만 유지됩니다. 닫기 전에 “저장됨”을 확인하세요.', '기기 간 동기화와 장애 복구를 개선합니다.', '프로필, 수동 백업과 복원, 피드백 양식을 제공하고 광고 없는 무료 베타로 일상 사용을 검증합니다.'),
  es: copy('Añadimos acceso con Google y guardado automático en la nube de notas, bandejas y ajustes. Recupera tu espacio al recargar o volver a iniciar sesión. Puedes reintentar los guardados fallidos; los cambios en conflicto no se sobrescriben automáticamente.', 'Inicia sesión con Google para guardar. Las notas de invitado son temporales. Espera a ver «Guardado» antes de cerrar.', 'Mejorar la sincronización entre dispositivos y la recuperación ante fallos.', 'Perfiles, copias de seguridad y restauración manuales, y un formulario de comentarios; una beta gratuita sin anuncios para validar el uso diario.'),
  fr: copy('Ajout de la connexion Google et de l’enregistrement automatique des notes, des plateaux et des réglages dans le cloud. Retrouvez votre espace après un rechargement ou une reconnexion. Réessayez les enregistrements échoués ; les modifications en conflit ne sont pas écrasées automatiquement.', 'Connectez-vous avec Google pour enregistrer. Les notes sans connexion sont temporaires. Attendez « Enregistré » avant de fermer.', 'Améliorer la synchronisation entre appareils et la récupération après incident.', 'Profils, sauvegarde et restauration manuelles, formulaire de commentaires et bêta gratuite sans publicité pour évaluer l’usage quotidien.'),
  'pt-BR': copy('Adicionamos login com Google e salvamento automático de notas, bandejas e configurações na nuvem. Restaure seu espaço ao recarregar ou entrar novamente. Você pode tentar salvar de novo em caso de falha; alterações em conflito não são sobrescritas automaticamente.', 'Entre com o Google para salvar. Notas de visitantes são temporárias. Aguarde “Salvo” antes de fechar.', 'Melhorar a sincronização entre dispositivos e a recuperação de falhas.', 'Perfis, backup e restauração manuais e formulário de feedback; uma versão beta gratuita sem anúncios para validar o uso diário.'),
  hi: copy('Google साइन-इन और मेमो, ट्रे व सेटिंग का स्वचालित क्लाउड सेव जोड़ा गया है। पेज दोबारा लोड करने या फिर साइन इन करने पर अपना कार्यक्षेत्र बहाल करें। सेव विफल होने पर फिर कोशिश कर सकते हैं; टकराने वाले बदलाव अपने आप ओवरराइट नहीं होते।', 'सहेजने के लिए Google से साइन इन करें। बिना साइन-इन वाले मेमो अस्थायी हैं। बंद करने से पहले “सहेजा गया” देखें।', 'डिवाइसों के बीच सिंक और विफलता से पुनर्प्राप्ति को बेहतर बनाना।', 'प्रोफ़ाइल, मैन्युअल बैकअप और बहाली, फ़ीडबैक फ़ॉर्म तथा रोज़मर्रा के उपयोग की जाँच के लिए विज्ञापन-मुक्त मुफ़्त बीटा।'),
  ar: copy('أُضيف تسجيل الدخول باستخدام Google والحفظ التلقائي للملاحظات والأدراج والإعدادات في السحابة. استعد مساحة عملك بعد إعادة التحميل أو تسجيل الدخول مجددًا. يمكن إعادة محاولة الحفظ الفاشل، ولا تُستبدل التغييرات المتعارضة تلقائيًا.', 'سجّل الدخول باستخدام Google للحفظ. ملاحظات الضيف مؤقتة. انتظر ظهور «تم الحفظ» قبل الإغلاق.', 'تحسين المزامنة بين الأجهزة والتعافي من الأعطال.', 'ملفات شخصية ونسخ احتياطي واستعادة يدويان ونموذج ملاحظات، مع نسخة تجريبية مجانية بلا إعلانات لاختبار الاستخدام اليومي.'),
  ru: copy('Добавлены вход через Google и автоматическое сохранение заметок, лотков и настроек в облаке. Рабочее пространство восстанавливается после перезагрузки или повторного входа. Неудачное сохранение можно повторить; конфликтующие изменения не перезаписываются автоматически.', 'Войдите через Google для сохранения. Гостевые заметки временные. Перед закрытием дождитесь статуса «Сохранено».', 'Улучшить синхронизацию между устройствами и восстановление после сбоев.', 'Профили, ручное резервное копирование и восстановление, форма обратной связи и бесплатная бета без рекламы для проверки повседневного использования.'),
  id: copy('Login Google dan penyimpanan otomatis memo, baki, serta pengaturan ke cloud telah ditambahkan. Pulihkan ruang kerja setelah memuat ulang atau masuk kembali. Penyimpanan yang gagal dapat dicoba lagi, dan perubahan yang bertentangan tidak ditimpa otomatis.', 'Masuk dengan Google untuk menyimpan. Memo tamu bersifat sementara. Tunggu “Tersimpan” sebelum menutup.', 'Meningkatkan sinkronisasi antarperangkat dan pemulihan gangguan.', 'Profil, pencadangan dan pemulihan manual, serta formulir masukan; beta gratis tanpa iklan untuk menguji penggunaan sehari-hari.'),
};
