import type { Lang } from '@/app/languages';

export interface ReleaseCopy {
  preview: string;
  warning: string;
  roadmapTitle: string;
  next: string;
  later: string;
  future: string;
  nextBody: string;
  laterBody: string;
  futureBody: string;
  roadmapNote: string;
  updates: string;
  allUpdates: string;
  releaseSummary: string;
  historyTitle: string;
  historyNote: string;
  historyLatest: string;
  historyPins: string;
  historyCreation: string;
  back: string;
  planned: string;
}

export const releaseCopy: Record<Lang, ReleaseCopy> = {
  "en": {
    "preview": "Web Preview",
    "warning": "Data is not saved yet. Reloading may lose your memos.",
    "roadmapTitle": "What’s next",
    "next": "Next",
    "later": "Later",
    "future": "Future plans",
    "nextBody": "Backup and restore, then Google sign-in, saving, sync and recovery.",
    "laterBody": "Profiles, version updates and a feedback form; an ad-free beta to validate everyday use.",
    "futureBody": "Notion / Obsidian / Evernote import, Codex MCP, memo sharing, paid plans and native iOS / Android apps.",
    "roadmapNote": "Plans may change. No release dates are promised; paid plans follow beta validation.",
    "updates": "Updates",
    "allUpdates": "All updates",
    "releaseSummary": "Public version tracking starts at 0.1.0. The roadmap and update history are now available.",
    "historyTitle": "Implementation history",
    "historyNote": "Selected changes before version tracking, grouped by implementation date. No past version numbers have been assigned.",
    "historyLatest": "Compact editing toolbar with Undo / Redo first and an expandable color palette.",
    "historyPins": "Pinnable, collapsible trays and memos; in-note search.",
    "historyCreation": "Inline tray and memo creation, tray renaming, and a fix for code blocks disappearing during Rich conversion.",
    "back": "Back to Drafta",
    "planned": "Planned"
  },
  "ja": {
    "preview": "Web試験公開",
    "warning": "データ保存は未対応です. 再読み込みでメモが失われる場合があります.",
    "roadmapTitle": "今後の実装計画",
    "next": "次に実装",
    "later": "その後",
    "future": "将来構想",
    "nextBody": "バックアップ･復元を整え, Googleログイン･永続保存･同期･障害復旧へ進みます.",
    "laterBody": "プロファイル, バージョン更新情報, フィードバックフォームを用意し, 広告なしの無料βで実用性を検証します.",
    "futureBody": "Notion / Obsidian / Evernoteからのインポート, Codex向けMCP, Memo共有, 有料プラン, iOS / Androidネイティブアプリを計画しています.",
    "roadmapNote": "計画は変更される場合があります. 公開日は未定です. 有料化は無料βの検証後に判断します.",
    "updates": "更新情報",
    "allUpdates": "すべての更新履歴",
    "releaseSummary": "0.1.0から公開バージョンの運用を開始します. 実装計画と更新履歴を確認できるようになりました.",
    "historyTitle": "これまでの主な実装",
    "historyNote": "バージョン運用前の主な変更を実装日ごとに掲載しています. 過去の番号は後付けしていません.",
    "historyLatest": "編集ツールバーをコンパクト化し, Undo / Redoを先頭へ, カラーパレットを開閉式へ変更しました.",
    "historyPins": "Tray･Memoのピン留めと折りたたみ, ノート内検索に対応しました.",
    "historyCreation": "Tray･Memoの一覧内作成とTrayの改名に対応し, Rich変換でコードブロックが消える不具合を修正しました.",
    "back": "Draftaへ戻る",
    "planned": "予定"
  },
  "zh-CN": {
    "preview": "Web预览版",
    "warning": "尚不支持数据保存。重新加载可能导致备忘录丢失。",
    "roadmapTitle": "后续计划",
    "next": "下一步",
    "later": "随后",
    "future": "未来计划",
    "nextBody": "先实现备份与恢复，再加入Google登录、持久保存、同步和故障恢复。",
    "laterBody": "提供配置档案、版本更新信息和反馈表单，并通过无广告的免费测试版验证日常使用。",
    "futureBody": "计划支持Notion / Obsidian / Evernote导入、Codex MCP、备忘录分享、付费方案及iOS / Android原生应用。",
    "roadmapNote": "计划可能调整，发布日期未定。付费方案将在免费测试验证后决定。",
    "updates": "更新",
    "allUpdates": "全部更新",
    "releaseSummary": "从0.1.0开始公开版本管理，新增开发计划与更新历史。",
    "historyTitle": "主要实现记录",
    "historyNote": "按实现日期整理版本管理前的主要变更，不追溯分配版本号。",
    "historyLatest": "编辑工具栏更加紧凑，Undo / Redo优先显示，调色板可展开。",
    "historyPins": "支持托盘和备忘录的固定与折叠，以及笔记内搜索。",
    "historyCreation": "支持在列表中创建托盘与备忘录、重命名托盘，并修复富文本转换时的代码块丢失问题。",
    "back": "返回Drafta",
    "planned": "计划中"
  },
  "ko": {
    "preview": "웹 미리보기",
    "warning": "아직 데이터가 저장되지 않습니다. 새로고침하면 메모가 사라질 수 있습니다.",
    "roadmapTitle": "개발 계획",
    "next": "다음 단계",
    "later": "이후",
    "future": "향후 계획",
    "nextBody": "백업과 복원부터 시작해 Google 로그인, 영구 저장, 동기화와 장애 복구를 구현합니다.",
    "laterBody": "프로필, 버전 업데이트 안내와 피드백 양식을 마련하고 광고 없는 무료 베타로 사용성을 검증합니다.",
    "futureBody": "Notion / Obsidian / Evernote 가져오기, Codex MCP, 메모 공유, 유료 요금제와 iOS / Android 네이티브 앱을 계획합니다.",
    "roadmapNote": "계획은 변경될 수 있으며 출시일은 미정입니다. 유료화는 무료 베타 검증 후 결정합니다.",
    "updates": "업데이트",
    "allUpdates": "모든 업데이트",
    "releaseSummary": "0.1.0부터 공개 버전 관리를 시작합니다. 개발 계획과 업데이트 기록을 확인할 수 있습니다.",
    "historyTitle": "주요 구현 기록",
    "historyNote": "버전 관리 이전의 주요 변경을 구현 날짜별로 정리했습니다. 과거 버전 번호는 부여하지 않았습니다.",
    "historyLatest": "편집 도구 모음을 간결하게 구성하고 Undo / Redo를 먼저 표시하며 색상 팔레트를 접을 수 있습니다.",
    "historyPins": "트레이와 메모의 고정 및 접기, 노트 내 검색을 지원합니다.",
    "historyCreation": "목록에서 트레이와 메모 생성, 트레이 이름 변경을 지원하고 리치 변환 시 코드 블록이 사라지는 문제를 수정했습니다.",
    "back": "Drafta로 돌아가기",
    "planned": "예정"
  },
  "es": {
    "preview": "Vista previa web",
    "warning": "Los datos aún no se guardan. Al recargar podrías perder tus notas.",
    "roadmapTitle": "Próximos pasos",
    "next": "A continuación",
    "later": "Después",
    "future": "Planes futuros",
    "nextBody": "Copias de seguridad y restauración, seguidas de acceso con Google, guardado, sincronización y recuperación.",
    "laterBody": "Perfiles, novedades de versiones y formulario de comentarios; una beta gratuita sin anuncios para validar el uso diario.",
    "futureBody": "Importación de Notion / Obsidian / Evernote, MCP para Codex, notas compartidas, planes de pago y apps nativas para iOS / Android.",
    "roadmapNote": "Los planes pueden cambiar. No hay fechas comprometidas; los planes de pago seguirán a la validación de la beta.",
    "updates": "Novedades",
    "allUpdates": "Todas las novedades",
    "releaseSummary": "El registro público de versiones comienza en 0.1.0. Ya están disponibles la hoja de ruta y el historial.",
    "historyTitle": "Historial de implementación",
    "historyNote": "Cambios destacados anteriores al registro de versiones, agrupados por fecha de implementación, sin números retroactivos.",
    "historyLatest": "Barra de edición compacta, Undo / Redo primero y paleta de colores desplegable.",
    "historyPins": "Bandejas y notas fijadas y plegables, y búsqueda dentro de la nota.",
    "historyCreation": "Creación de bandejas y notas en la lista, renombrado de bandejas y corrección de bloques de código que desaparecían al convertir a texto enriquecido.",
    "back": "Volver a Drafta",
    "planned": "Previsto"
  },
  "fr": {
    "preview": "Aperçu web",
    "warning": "Les données ne sont pas encore enregistrées. Un rechargement peut effacer vos notes.",
    "roadmapTitle": "À venir",
    "next": "Prochaine étape",
    "later": "Ensuite",
    "future": "Projets futurs",
    "nextBody": "Sauvegarde et restauration, puis connexion Google, enregistrement durable, synchronisation et récupération.",
    "laterBody": "Profils, annonces de versions et formulaire de retour ; une bêta gratuite sans publicité pour valider l’usage quotidien.",
    "futureBody": "Import Notion / Obsidian / Evernote, MCP pour Codex, partage de notes, offres payantes et applications natives iOS / Android.",
    "roadmapNote": "Les projets peuvent évoluer. Aucune date n’est promise ; les offres payantes suivront la validation de la bêta.",
    "updates": "Nouveautés",
    "allUpdates": "Toutes les mises à jour",
    "releaseSummary": "Le suivi public des versions commence à 0.1.0. La feuille de route et l’historique sont désormais disponibles.",
    "historyTitle": "Historique des réalisations",
    "historyNote": "Principaux changements antérieurs au suivi des versions, classés par date de réalisation, sans numérotation rétroactive.",
    "historyLatest": "Barre d’édition compacte, Undo / Redo en premier et palette de couleurs dépliable.",
    "historyPins": "Bacs et notes épinglés et repliables, avec recherche dans la note.",
    "historyCreation": "Création de bacs et de notes dans la liste, renommage des bacs et correction de la disparition des blocs de code lors de la conversion en texte enrichi.",
    "back": "Retour à Drafta",
    "planned": "Prévu"
  },
  "pt-BR": {
    "preview": "Prévia web",
    "warning": "Os dados ainda não são salvos. Recarregar pode apagar suas notas.",
    "roadmapTitle": "Próximos passos",
    "next": "A seguir",
    "later": "Depois",
    "future": "Planos futuros",
    "nextBody": "Backup e restauração, seguidos de login com Google, armazenamento persistente, sincronização e recuperação.",
    "laterBody": "Perfis, novidades de versões e formulário de feedback; uma beta gratuita sem anúncios para validar o uso diário.",
    "futureBody": "Importação de Notion / Obsidian / Evernote, MCP para Codex, compartilhamento de notas, planos pagos e apps nativos iOS / Android.",
    "roadmapNote": "Os planos podem mudar. Não há datas prometidas; os planos pagos virão após a validação da beta.",
    "updates": "Novidades",
    "allUpdates": "Todas as atualizações",
    "releaseSummary": "O histórico público de versões começa em 0.1.0. O roteiro de desenvolvimento e o histórico estão disponíveis.",
    "historyTitle": "Histórico de implementação",
    "historyNote": "Principais mudanças anteriores ao controle de versões, por data de implementação, sem números retroativos.",
    "historyLatest": "Barra de edição compacta, Undo / Redo primeiro e paleta de cores expansível.",
    "historyPins": "Bandejas e notas fixadas e recolhíveis, além de busca dentro da nota.",
    "historyCreation": "Criação de bandejas e notas na lista, renomeação de bandejas e correção de blocos de código que desapareciam na conversão para texto rico.",
    "back": "Voltar ao Drafta",
    "planned": "Planejado"
  },
  "hi": {
    "preview": "वेब पूर्वावलोकन",
    "warning": "डेटा अभी सहेजा नहीं जाता है। पेज दोबारा लोड करने पर मेमो खो सकते हैं।",
    "roadmapTitle": "आगे की योजना",
    "next": "अगला चरण",
    "later": "उसके बाद",
    "future": "भविष्य की योजनाएँ",
    "nextBody": "पहले बैकअप और बहाली, फिर Google लॉगिन, स्थायी भंडारण, सिंक और विफलता से पुनर्प्राप्ति।",
    "laterBody": "प्रोफ़ाइल, संस्करण अपडेट और फ़ीडबैक फ़ॉर्म; रोज़मर्रा के उपयोग की जाँच के लिए विज्ञापन रहित मुफ़्त बीटा।",
    "futureBody": "Notion / Obsidian / Evernote से आयात, Codex MCP, मेमो साझा करना, सशुल्क योजनाएँ और iOS / Android के नेटिव ऐप।",
    "roadmapNote": "योजनाएँ बदल सकती हैं। रिलीज़ की तारीखें तय नहीं हैं। सशुल्क योजनाएँ बीटा के मूल्यांकन के बाद तय होंगी।",
    "updates": "अपडेट",
    "allUpdates": "सभी अपडेट",
    "releaseSummary": "सार्वजनिक संस्करण क्रम 0.1.0 से शुरू होता है। विकास योजना और अपडेट इतिहास अब उपलब्ध हैं।",
    "historyTitle": "मुख्य कार्यान्वयन इतिहास",
    "historyNote": "संस्करण क्रम शुरू होने से पहले के मुख्य बदलाव, कार्यान्वयन की तारीख के अनुसार। पुराने बदलावों को संस्करण संख्या नहीं दी गई है।",
    "historyLatest": "संपादन टूलबार छोटा किया गया; Undo / Redo पहले दिखते हैं और रंग पैलेट खोला जा सकता है।",
    "historyPins": "ट्रे और मेमो को पिन करने और समेटने के साथ नोट के अंदर खोज जोड़ी गई।",
    "historyCreation": "सूची में ट्रे और मेमो बनाना, ट्रे का नाम बदलना और रिच रूपांतरण में कोड ब्लॉक गायब होने की समस्या का सुधार।",
    "back": "Drafta पर वापस जाएँ",
    "planned": "नियोजित"
  },
  "ar": {
    "preview": "معاينة الويب",
    "warning": "لا تُحفظ البيانات بعد. قد تفقد مذكراتك عند إعادة تحميل الصفحة.",
    "roadmapTitle": "خطة التطوير",
    "next": "الخطوة التالية",
    "later": "بعد ذلك",
    "future": "خطط مستقبلية",
    "nextBody": "النسخ الاحتياطي والاستعادة، ثم تسجيل الدخول باستخدام Google والحفظ الدائم والمزامنة والتعافي من الأعطال.",
    "laterBody": "الملفات الشخصية وتحديثات الإصدارات ونموذج الملاحظات؛ ونسخة تجريبية مجانية بلا إعلانات لاختبار الاستخدام اليومي.",
    "futureBody": "الاستيراد من Notion / Obsidian / Evernote، وربط Codex عبر MCP، ومشاركة المذكرات، وخطط مدفوعة وتطبيقات أصلية لـ iOS / Android.",
    "roadmapNote": "قد تتغير الخطط. لم تُحدد مواعيد الإطلاق؛ وتُقرر الخطط المدفوعة بعد تقييم النسخة التجريبية.",
    "updates": "التحديثات",
    "allUpdates": "جميع التحديثات",
    "releaseSummary": "يبدأ ترقيم الإصدارات العامة من 0.1.0. أصبحت خطة التطوير وسجل التحديثات متاحين.",
    "historyTitle": "أبرز مراحل التنفيذ",
    "historyNote": "أبرز التغييرات السابقة لترقيم الإصدارات، حسب تاريخ التنفيذ، دون إسناد أرقام إصدارات بأثر رجعي.",
    "historyLatest": "شريط تحرير أكثر اختصارًا مع Undo / Redo أولًا ولوحة ألوان قابلة للفتح.",
    "historyPins": "تثبيت الأدراج والمذكرات وطيها، والبحث داخل الملاحظة.",
    "historyCreation": "إنشاء الأدراج والمذكرات داخل القائمة وإعادة تسمية الأدراج، وإصلاح اختفاء كتل التعليمات البرمجية عند التحويل إلى النص المنسق.",
    "back": "العودة إلى Drafta",
    "planned": "مخطط"
  },
  "ru": {
    "preview": "Веб-предпросмотр",
    "warning": "Данные пока не сохраняются. При перезагрузке заметки могут быть потеряны.",
    "roadmapTitle": "Планы развития",
    "next": "Следующий шаг",
    "later": "Затем",
    "future": "Будущие планы",
    "nextBody": "Резервное копирование и восстановление, затем вход через Google, постоянное хранение, синхронизация и восстановление после сбоев.",
    "laterBody": "Профили, новости версий и форма обратной связи; бесплатная бета без рекламы для проверки повседневного использования.",
    "futureBody": "Импорт из Notion / Obsidian / Evernote, MCP для Codex, общий доступ к заметкам, платные планы и нативные приложения iOS / Android.",
    "roadmapNote": "Планы могут измениться. Даты не обещаны; платные планы будут определены после проверки беты.",
    "updates": "Обновления",
    "allUpdates": "Все обновления",
    "releaseSummary": "Публичная нумерация версий начинается с 0.1.0. Теперь доступны план развития и история обновлений.",
    "historyTitle": "Основные этапы разработки",
    "historyNote": "Основные изменения до введения версий сгруппированы по дате реализации, без присвоения номеров задним числом.",
    "historyLatest": "Компактная панель редактирования с Undo / Redo в начале и раскрывающейся палитрой.",
    "historyPins": "Закрепление и сворачивание лотков и заметок, поиск внутри заметки.",
    "historyCreation": "Создание лотков и заметок в списке, переименование лотков и исправление исчезающих блоков кода при преобразовании в форматированный текст.",
    "back": "Вернуться в Drafta",
    "planned": "Запланировано"
  },
  "id": {
    "preview": "Pratinjau web",
    "warning": "Data belum disimpan. Memuat ulang halaman dapat menghilangkan memo Anda.",
    "roadmapTitle": "Rencana pengembangan",
    "next": "Berikutnya",
    "later": "Setelah itu",
    "future": "Rencana mendatang",
    "nextBody": "Pencadangan dan pemulihan, lalu login Google, penyimpanan permanen, sinkronisasi dan pemulihan gangguan.",
    "laterBody": "Profil, kabar versi dan formulir masukan; beta gratis tanpa iklan untuk menguji penggunaan sehari-hari.",
    "futureBody": "Impor Notion / Obsidian / Evernote, MCP untuk Codex, berbagi memo, paket berbayar dan aplikasi native iOS / Android.",
    "roadmapNote": "Rencana dapat berubah. Tanggal rilis belum dijanjikan; paket berbayar ditentukan setelah evaluasi beta.",
    "updates": "Pembaruan",
    "allUpdates": "Semua pembaruan",
    "releaseSummary": "Penomoran versi publik dimulai dari 0.1.0. Rencana pengembangan dan riwayat pembaruan kini tersedia.",
    "historyTitle": "Riwayat implementasi utama",
    "historyNote": "Perubahan utama sebelum penomoran versi, berdasarkan tanggal implementasi, tanpa nomor versi retroaktif.",
    "historyLatest": "Bilah penyuntingan ringkas dengan Undo / Redo di awal dan palet warna yang dapat dibuka.",
    "historyPins": "Penyematan dan pelipatan baki serta memo, dan pencarian dalam catatan.",
    "historyCreation": "Pembuatan baki dan memo di daftar, penggantian nama baki, serta perbaikan blok kode yang hilang saat konversi ke teks kaya.",
    "back": "Kembali ke Drafta",
    "planned": "Direncanakan"
  }
};
