import type { Lang } from '@/app/languages';

// Phrase order is shared across locales and validated by sample-notes.test.ts.
// Keep code examples and keyboard notation out of the translation catalog.
export const sampleCopy: Record<Lang, { welcome: string[]; reference: string[] }> = {
  en: {
    welcome: ['Welcome to Drafta', 'Organize to-dos and thoughts seamlessly.', 'Put your tasks in ToDo app, memos in note-taking app.', 'Every thought in one place, Drafta!', 'Before', 'After', 'Scattered notes', 'Structured Knowledge', 'Rough thought', 'Polished ideas', "Move forward, feel lighter."],
    reference: ['Quick Reference', 'Drafta supports standard Markdown syntax and powerful rich text features.', 'Text Styling', 'Bold', 'or', 'Italic', 'Strikethrough', 'Inline Code', 'Color Tags', 'Green', '- Success, Growth', 'Blue', '- Info, Links', 'Purple', '- Creative, Special', 'Rose', '- Important, Highlight', 'Gold', '- Warning, Priority', 'Grey', '- Muted, Secondary', 'Lists & Structure', 'Bullet List', 'Item A', 'Item B', 'Numbered List (Smart!)', 'Define your goal', 'What do you want to achieve?', 'Break it into steps', 'Small tasks are easier to tackle', 'Execute daily', 'Consistency beats intensity', 'Review & iterate', 'Adjust based on results', 'Tip: Use Enter to continue numbering naturally.', 'Task List', 'Todo item', 'Done item', 'Quote', ': Use', 'at the start of a line to create a blockquote.', 'Advanced', 'Code Blocks', 'Tables', 'Feature', 'Status', 'Done', 'Rich Text', 'Drafta Power Tips', 'List Style', ': Choose Top or Bottom in Settings.', 'Organization', ': In Manual order, drag to reorder. On touch screens, hold first, then move.', 'Focus Mode', ': Collapse the sidebar for distraction-free writing.', 'Shortcuts', 'to insert blocks. Type to filter, use ↑/↓ and Enter, or click. Esc closes the menu.'],
  },
  ja: {
    welcome: ['Draftaへようこそ', 'やることと思いつきを、ひとつに整理。', 'タスクはToDoアプリ、メモはメモアプリに分けて管理。', 'すべての思いつきを、Draftaひとつに！', 'これまで', 'これから', '散らばったメモ', '整理された知識', '思いつきの断片', '磨かれたアイデア', 'ここから、もっと軽やかに！'],
    reference: ['クイックリファレンス', 'Draftaは、標準的なMarkdown記法と多彩なリッチテキスト機能に対応しています。', '文字の装飾', '太字', 'または', '斜体', '取り消し線', 'インラインコード', '文字色', '緑', '- 成功・成長', '青', '- 情報・リンク', '紫', '- 創造性・特別な内容', 'ローズ', '- 重要・強調', 'ゴールド', '- 注意・優先事項', 'グレー', '- 控えめな内容・補足', 'リストと構成', '箇条書き', '項目A', '項目B', '番号付きリスト', '目標を決める', '何を実現したいですか？', '手順に分ける', '小さなタスクなら取り組みやすくなります', '毎日取り組む', '一度の頑張りより継続を大切に', '振り返って改善する', '結果に合わせて調整します', 'ヒント：Enterキーで、番号付きリストを続けられます。', 'タスクリスト', '未完了の項目', '完了した項目', '引用', '：行頭に', 'を入力すると、引用ブロックを作れます。', '応用', 'コードブロック', '表', '機能', '状態', '完了', 'リッチテキスト', 'Drafta活用のヒント', 'リストの追加位置', '：設定で「上に追加」または「下に追加」を選べます。', '整理', '：手動順ではドラッグで並べ替えられます。タッチ操作では長押ししてから動かします。', '集中モード', '：サイドバーを閉じて、書くことに集中できます。', 'ショートカット', 'で挿入メニューを開きます。文字で絞り込み、↑↓とEnter、またはクリックで選択します。Escで閉じます。'],
  },
  'zh-CN': {
    welcome: ['欢迎使用Drafta', '轻松整合待办事项与灵感。', '任务放在待办应用，笔记放在笔记应用。', '所有想法，尽在Drafta！', '之前', '之后', '零散的笔记', '有条理的知识', '初步的想法', '完善的创意', '从这里开始，让思路更顺畅！'],
    reference: ['快速参考', 'Drafta支持标准Markdown语法和丰富的富文本功能。', '文字样式', '粗体', '或', '斜体', '删除线', '行内代码', '文字颜色', '绿色', '- 成功、成长', '蓝色', '- 信息、链接', '紫色', '- 创意、特别内容', '玫瑰色', '- 重要、强调', '金色', '- 提醒、优先事项', '灰色', '- 次要内容、补充说明', '列表与结构', '项目符号列表', '项目A', '项目B', '智能编号列表', '确定目标', '你想实现什么？', '拆分步骤', '小任务更容易着手', '每天行动', '坚持比一时的强度更重要', '回顾与改进', '根据结果进行调整', '提示：按Enter键可继续编号列表。', '任务列表', '待办项目', '已完成项目', '引用', '：在行首输入', '即可创建引用块。', '进阶功能', '代码块', '表格', '功能', '状态', '已完成', '富文本', 'Drafta使用技巧', '列表样式', '：在设置中选择添加到顶部或底部。', '整理', '：在手动排序模式下拖动即可排序。触摸屏上请先长按再移动。', '专注模式', '：收起侧边栏，专心写作。', '快捷操作', '可打开插入菜单。输入文字筛选，用↑↓和Enter或点击选择，按Esc关闭。'],
  },
  ko: {
    welcome: ['Drafta에 오신 것을 환영합니다', '할 일과 생각을 한곳에서 자연스럽게 정리하세요.', '할 일은 할 일 앱에, 메모는 메모 앱에 따로 저장하나요?', '모든 생각을 한곳에, Drafta!', '이전', '이후', '흩어진 메모', '체계적인 지식', '다듬지 않은 생각', '정리된 아이디어', '이제 더 가볍게 나아가세요!'],
    reference: ['빠른 사용 안내', 'Drafta는 표준 Markdown 문법과 다양한 서식 기능을 지원합니다.', '텍스트 서식', '굵게', '또는', '기울임꼴', '취소선', '인라인 코드', '텍스트 색상', '초록', '- 성공, 성장', '파랑', '- 정보, 링크', '보라', '- 창의성, 특별한 내용', '로즈', '- 중요, 강조', '골드', '- 주의, 우선순위', '회색', '- 부가 정보, 보조 내용', '목록과 구조', '글머리 기호 목록', '항목 A', '항목 B', '스마트 번호 목록', '목표 정하기', '무엇을 이루고 싶으신가요?', '단계로 나누기', '작은 작업부터 시작하면 수월합니다', '매일 실행하기', '한 번의 강도보다 꾸준함이 중요합니다', '돌아보고 개선하기', '결과에 따라 조정하세요', '팁: Enter를 누르면 번호 목록이 이어집니다.', '할 일 목록', '할 일 항목', '완료한 항목', '인용', ': 줄 시작에', '를 입력하면 인용문을 만들 수 있습니다.', '고급 기능', '코드 블록', '표', '기능', '상태', '완료', '서식 있는 텍스트', 'Drafta 활용 팁', '목록 스타일', ': 설정에서 위에 추가 또는 아래에 추가를 선택하세요.', '정리', ': 수동 정렬에서는 드래그하여 순서를 바꿀 수 있습니다. 터치 화면에서는 길게 누른 후 움직이세요.', '집중 모드', ': 사이드바를 접고 글쓰기에 집중하세요.', '바로 가기', '로 삽입 메뉴를 여세요. 입력하여 검색하고 ↑↓와 Enter 또는 클릭으로 선택하세요. Esc로 닫습니다.'],
  },
  hi: {
    welcome: ['Drafta में आपका स्वागत है', 'कामों और विचारों को आसानी से एक जगह व्यवस्थित करें।', 'कामों के लिए अलग ऐप और नोट्स के लिए अलग ऐप।', 'हर विचार एक जगह, Drafta में!', 'पहले', 'बाद में', 'बिखरे हुए नोट्स', 'व्यवस्थित जानकारी', 'शुरुआती सोच', 'निखरे हुए विचार', 'अब आगे बढ़ना और आसान है!'],
    reference: ['त्वरित संदर्भ', 'Drafta में मानक Markdown सिंटैक्स और समृद्ध टेक्स्ट फ़ॉर्मैटिंग सुविधाएँ उपलब्ध हैं।', 'टेक्स्ट की शैली', 'बोल्ड', 'या', 'इटैलिक', 'काटा हुआ टेक्स्ट', 'इनलाइन कोड', 'टेक्स्ट के रंग', 'हरा', '- सफलता, विकास', 'नीला', '- जानकारी, लिंक', 'बैंगनी', '- रचनात्मकता, विशेष सामग्री', 'गुलाबी', '- महत्वपूर्ण, हाइलाइट', 'सुनहरा', '- चेतावनी, प्राथमिकता', 'धूसर', '- कम प्रमुख, अतिरिक्त जानकारी', 'सूचियाँ और संरचना', 'बुलेट सूची', 'मद A', 'मद B', 'स्मार्ट क्रमांकित सूची', 'अपना लक्ष्य तय करें', 'आप क्या हासिल करना चाहते हैं?', 'छोटे चरणों में बाँटें', 'छोटे काम शुरू करना आसान होता है', 'रोज़ काम करें', 'तीव्रता से अधिक ज़रूरी निरंतरता है', 'समीक्षा करें और सुधारें', 'नतीजों के अनुसार बदलाव करें', 'सुझाव: क्रमांकित सूची जारी रखने के लिए Enter दबाएँ।', 'कार्य सूची', 'बाकी काम', 'पूरा हुआ काम', 'उद्धरण', ': पंक्ति की शुरुआत में', 'लिखकर उद्धरण ब्लॉक बनाएँ।', 'उन्नत सुविधाएँ', 'कोड ब्लॉक', 'तालिकाएँ', 'सुविधा', 'स्थिति', 'पूरा', 'रिच टेक्स्ट', 'Drafta के उपयोगी सुझाव', 'सूची की शैली', ': सेटिंग्स में ऊपर या नीचे जोड़ने का विकल्प चुनें।', 'व्यवस्था', ': मैन्युअल क्रम में खींचकर क्रम बदलें। टच स्क्रीन पर पहले दबाकर रखें, फिर खिसकाएँ।', 'एकाग्रता मोड', ': बिना ध्यान भटके लिखने के लिए साइडबार बंद करें।', 'शॉर्टकट', 'से ब्लॉक जोड़ने का मेनू खोलें। खोजने के लिए टाइप करें, ↑↓ और Enter या क्लिक से चुनें। Esc से बंद करें।'],
  },
  ar: {
    welcome: ['مرحبًا بك في Drafta', 'نظّم المهام والأفكار معًا بسلاسة.', 'المهام في تطبيق للمهام، والملاحظات في تطبيق آخر.', 'كل أفكارك في مكان واحد، Drafta!', 'قبل', 'بعد', 'ملاحظات متفرقة', 'معرفة منظمة', 'أفكار أولية', 'أفكار مصقولة', 'انطلق الآن بخطوات أكثر سلاسة!'],
    reference: ['مرجع سريع', 'يدعم Drafta صيغة Markdown القياسية وميزات تنسيق النص الغني.', 'تنسيق النص', 'عريض', 'أو', 'مائل', 'يتوسطه خط', 'كود مضمّن', 'ألوان النص', 'أخضر', '- النجاح والنمو', 'أزرق', '- المعلومات والروابط', 'بنفسجي', '- الإبداع والمحتوى المميز', 'وردي', '- الأهمية والإبراز', 'ذهبي', '- التنبيه والأولوية', 'رمادي', '- المحتوى الثانوي والتوضيحات', 'القوائم والبنية', 'قائمة نقطية', 'العنصر A', 'العنصر B', 'قائمة مرقمة ذكية', 'حدّد هدفك', 'ما الذي تريد تحقيقه؟', 'قسّمه إلى خطوات', 'المهام الصغيرة أسهل في التنفيذ', 'اعمل يوميًا', 'الاستمرار أهم من شدة الجهد', 'راجع وحسّن', 'عدّل بناءً على النتائج', 'نصيحة: اضغط Enter لمتابعة الترقيم.', 'قائمة المهام', 'مهمة لم تكتمل', 'مهمة مكتملة', 'اقتباس', ': استخدم', 'في بداية السطر لإنشاء كتلة اقتباس.', 'ميزات متقدمة', 'كتل الكود', 'الجداول', 'الميزة', 'الحالة', 'مكتمل', 'نص غني', 'نصائح لاستخدام Drafta', 'نمط القائمة', ': اختر الإضافة إلى الأعلى أو الأسفل من الإعدادات.', 'التنظيم', ': في الترتيب اليدوي، اسحب لتغيير الترتيب. على شاشة اللمس، اضغط مطولًا أولًا ثم حرّك.', 'وضع التركيز', ': اطوِ الشريط الجانبي للكتابة دون تشتيت.', 'الاختصارات', 'لفتح قائمة الإدراج. اكتب للتصفية، ثم اختر بالأسهم ↑↓ وEnter أو بالنقر. اضغط Esc للإغلاق.'],
  },
  ru: {
    welcome: ['Добро пожаловать в Drafta', 'Объединяйте задачи и мысли без лишних усилий.', 'Задачи — в одном приложении, заметки — в другом.', 'Все мысли в одном месте — в Drafta!', 'До', 'После', 'Разрозненные заметки', 'Упорядоченные знания', 'Наброски мыслей', 'Продуманные идеи', 'Теперь двигаться вперёд проще!'],
    reference: ['Краткий справочник', 'Drafta поддерживает стандартный синтаксис Markdown и расширенное форматирование текста.', 'Оформление текста', 'Жирный', 'или', 'Курсив', 'Зачёркнутый', 'Встроенный код', 'Цвета текста', 'Зелёный', '- Успех, развитие', 'Синий', '- Информация, ссылки', 'Фиолетовый', '- Творчество, особое содержание', 'Розовый', '- Важное, выделение', 'Золотой', '- Предупреждение, приоритет', 'Серый', '- Второстепенное, пояснения', 'Списки и структура', 'Маркированный список', 'Пункт A', 'Пункт B', 'Умный нумерованный список', 'Определите цель', 'Чего вы хотите достичь?', 'Разбейте на шаги', 'За небольшие задачи легче взяться', 'Действуйте ежедневно', 'Регулярность важнее интенсивности', 'Анализируйте и улучшайте', 'Корректируйте действия по результатам', 'Совет: нажмите Enter, чтобы продолжить нумерацию.', 'Список задач', 'Невыполненная задача', 'Выполненная задача', 'Цитата', ': Используйте', 'в начале строки, чтобы создать блок цитаты.', 'Дополнительные возможности', 'Блоки кода', 'Таблицы', 'Функция', 'Статус', 'Готово', 'Форматированный текст', 'Полезные советы Drafta', 'Стиль списка', ': В настройках выберите добавление сверху или снизу.', 'Организация', ': В ручном порядке перетаскивайте заметки. На сенсорном экране сначала нажмите и удерживайте, затем переместите.', 'Режим фокусировки', ': Сверните боковую панель, чтобы писать без отвлечений.', 'Быстрые команды', 'открывает меню вставки. Введите запрос и выберите пункт с помощью ↑↓ и Enter или щелчком. Esc закрывает меню.'],
  },
  id: {
    welcome: ['Selamat datang di Drafta', 'Satukan tugas dan ide dengan mudah.', 'Tugas di aplikasi tugas, catatan di aplikasi catatan.', 'Semua ide di satu tempat, Drafta!', 'Sebelum', 'Sesudah', 'Catatan yang tersebar', 'Pengetahuan yang tertata', 'Gagasan awal', 'Ide yang matang', 'Kini Anda bisa melangkah lebih lancar!'],
    reference: ['Panduan Singkat', 'Drafta mendukung sintaks Markdown standar dan berbagai fitur pemformatan teks.', 'Gaya Teks', 'Tebal', 'atau', 'Miring', 'Coret', 'Kode Sebaris', 'Warna Teks', 'Hijau', '- Keberhasilan, pertumbuhan', 'Biru', '- Informasi, tautan', 'Ungu', '- Kreativitas, hal khusus', 'Merah Mawar', '- Penting, sorotan', 'Emas', '- Peringatan, prioritas', 'Abu-abu', '- Pelengkap, informasi sekunder', 'Daftar dan Struktur', 'Daftar Berpoin', 'Butir A', 'Butir B', 'Daftar Bernomor Cerdas', 'Tentukan tujuan', 'Apa yang ingin Anda capai?', 'Bagi menjadi langkah kecil', 'Tugas kecil lebih mudah dikerjakan', 'Kerjakan setiap hari', 'Konsistensi lebih penting daripada intensitas', 'Tinjau dan perbaiki', 'Sesuaikan berdasarkan hasil', 'Tips: tekan Enter untuk melanjutkan penomoran.', 'Daftar Tugas', 'Tugas belum selesai', 'Tugas selesai', 'Kutipan', ': Gunakan', 'di awal baris untuk membuat blok kutipan.', 'Fitur Lanjutan', 'Blok Kode', 'Tabel', 'Fitur', 'Status', 'Selesai', 'Teks Kaya', 'Tips Praktis Drafta', 'Gaya Daftar', ': Pilih tambah di atas atau di bawah melalui Pengaturan.', 'Pengaturan Catatan', ': Dalam urutan manual, seret untuk mengubah urutan. Pada layar sentuh, tekan lama dahulu, lalu geser.', 'Mode Fokus', ': Tutup bilah samping agar dapat menulis tanpa gangguan.', 'Pintasan', 'untuk membuka menu sisip. Ketik untuk mencari, pilih dengan ↑↓ dan Enter atau klik. Tekan Esc untuk menutup.'],
  },
  es: {
    welcome: ['Te damos la bienvenida a Drafta', 'Organiza tareas e ideas sin interrupciones.', 'Las tareas en una aplicación y las notas en otra.', '¡Todas tus ideas en un solo lugar, Drafta!', 'Antes', 'Después', 'Notas dispersas', 'Conocimiento organizado', 'Ideas en bruto', 'Ideas pulidas', '¡Ahora puedes avanzar con más fluidez!'],
    reference: ['Referencia rápida', 'Drafta admite la sintaxis estándar de Markdown y potentes funciones de texto enriquecido.', 'Formato de texto', 'Negrita', 'o', 'Cursiva', 'Tachado', 'Código en línea', 'Colores de texto', 'Verde', '- Éxito, crecimiento', 'Azul', '- Información, enlaces', 'Morado', '- Creatividad, contenido especial', 'Rosa', '- Importancia, énfasis', 'Dorado', '- Avisos, prioridad', 'Gris', '- Contenido secundario, aclaraciones', 'Listas y estructura', 'Lista con viñetas', 'Elemento A', 'Elemento B', 'Lista numerada inteligente', 'Define tu objetivo', '¿Qué quieres conseguir?', 'Divídelo en pasos', 'Las tareas pequeñas son más fáciles de abordar', 'Actúa cada día', 'La constancia importa más que la intensidad', 'Revisa y mejora', 'Ajusta según los resultados', 'Consejo: pulsa Enter para continuar la numeración.', 'Lista de tareas', 'Tarea pendiente', 'Tarea completada', 'Cita', ': Usa', 'al principio de una línea para crear una cita en bloque.', 'Funciones avanzadas', 'Bloques de código', 'Tablas', 'Función', 'Estado', 'Hecho', 'Texto enriquecido', 'Consejos para aprovechar Drafta', 'Estilo de lista', ': Elige añadir arriba o abajo en Ajustes.', 'Organización', ': En el orden manual, arrastra para reordenar. En pantallas táctiles, mantén pulsado y después mueve.', 'Modo de concentración', ': Oculta la barra lateral para escribir sin distracciones.', 'Atajos', 'para abrir el menú de inserción. Escribe para filtrar y selecciona con ↑↓ y Enter o con un clic. Esc cierra el menú.'],
  },
  fr: {
    welcome: ['Bienvenue dans Drafta', 'Organisez vos tâches et vos idées en toute simplicité.', 'Les tâches dans une application, les notes dans une autre.', 'Toutes vos idées au même endroit, dans Drafta !', 'Avant', 'Après', 'Notes éparpillées', 'Connaissances structurées', 'Ébauches de pensées', 'Idées affinées', 'Avancez désormais plus librement !'],
    reference: ['Guide rapide', 'Drafta prend en charge la syntaxe Markdown standard et de puissantes fonctions de texte enrichi.', 'Mise en forme du texte', 'Gras', 'ou', 'Italique', 'Barré', 'Code en ligne', 'Couleurs du texte', 'Vert', '- Réussite, progression', 'Bleu', '- Informations, liens', 'Violet', '- Créativité, contenu particulier', 'Rose', '- Importance, mise en évidence', 'Doré', '- Avertissement, priorité', 'Gris', '- Contenu secondaire, précisions', 'Listes et structure', 'Liste à puces', 'Élément A', 'Élément B', 'Liste numérotée intelligente', 'Définissez votre objectif', 'Que souhaitez-vous accomplir ?', 'Décomposez-le en étapes', 'Les petites tâches sont plus faciles à aborder', 'Agissez chaque jour', 'La régularité compte plus que l’intensité', 'Évaluez et améliorez', 'Adaptez-vous aux résultats', 'Astuce : appuyez sur Entrée pour poursuivre la numérotation.', 'Liste de tâches', 'Tâche à faire', 'Tâche terminée', 'Citation', ': Utilisez', 'au début d’une ligne pour créer un bloc de citation.', 'Fonctions avancées', 'Blocs de code', 'Tableaux', 'Fonction', 'État', 'Terminé', 'Texte enrichi', 'Conseils pour bien utiliser Drafta', 'Style de liste', ': Choisissez l’ajout en haut ou en bas dans les paramètres.', 'Organisation', ': En ordre manuel, faites glisser les notes pour les réorganiser. Sur écran tactile, maintenez d’abord le doigt appuyé, puis déplacez-le.', 'Mode concentration', ': Repliez la barre latérale pour écrire sans distraction.', 'Raccourcis', 'pour ouvrir le menu d’insertion. Saisissez du texte pour filtrer, puis choisissez avec ↑↓ et Entrée ou par clic. Échap ferme le menu.'],
  },
  'pt-BR': {
    welcome: ['Boas-vindas ao Drafta', 'Organize tarefas e ideias sem complicação.', 'Tarefas em um aplicativo, notas em outro.', 'Todas as ideias em um só lugar, no Drafta!', 'Antes', 'Depois', 'Notas espalhadas', 'Conhecimento organizado', 'Ideias iniciais', 'Ideias aprimoradas', 'Agora ficou mais fácil avançar!'],
    reference: ['Referência rápida', 'O Drafta oferece suporte à sintaxe padrão do Markdown e a recursos avançados de texto rico.', 'Formatação de texto', 'Negrito', 'ou', 'Itálico', 'Tachado', 'Código em linha', 'Cores do texto', 'Verde', '- Sucesso, crescimento', 'Azul', '- Informações, links', 'Roxo', '- Criatividade, conteúdo especial', 'Rosa', '- Importância, destaque', 'Dourado', '- Aviso, prioridade', 'Cinza', '- Conteúdo secundário, observações', 'Listas e estrutura', 'Lista com marcadores', 'Item A', 'Item B', 'Lista numerada inteligente', 'Defina seu objetivo', 'O que você quer alcançar?', 'Divida em etapas', 'Tarefas pequenas são mais fáceis de começar', 'Pratique todos os dias', 'A constância vale mais que a intensidade', 'Revise e melhore', 'Ajuste com base nos resultados', 'Dica: pressione Enter para continuar a numeração.', 'Lista de tarefas', 'Tarefa pendente', 'Tarefa concluída', 'Citação', ': Use', 'no início de uma linha para criar um bloco de citação.', 'Recursos avançados', 'Blocos de código', 'Tabelas', 'Recurso', 'Status', 'Concluído', 'Texto rico', 'Dicas para aproveitar o Drafta', 'Estilo de lista', ': Escolha adicionar no topo ou no fim nas configurações.', 'Organização', ': Na ordem manual, arraste para reordenar. Em telas sensíveis ao toque, mantenha pressionado antes de mover.', 'Modo de foco', ': Recolha a barra lateral para escrever sem distrações.', 'Atalhos', 'para abrir o menu de inserção. Digite para filtrar e escolha com ↑↓ e Enter ou clique. Esc fecha o menu.'],
  },
};
