import type { Lang } from '@/app/languages';
type Copy = { suffix: string; title: string; description: string; keepBoth: string; copied: string };
const copy = (suffix: string, title: string, description: string, keepBoth: string, copied: string): Copy => ({ suffix, title, description, keepBoth, copied });
export const syncCopy: Record<Lang, Copy> = {
  en: copy('Conflict copy', 'Review concurrent changes', 'Tray, order or deletion changes overlap. Keep the server version and settings, and add separate copies of this device’s trays and memos? Cancel keeps your unsaved edits on this device.', 'Keep both versions', 'Conflicting edits were kept as separate memo copies.'),
  ja: copy('競合コピー', '同時編集の内容を確認', 'Tray･順序･削除などの変更が重なりました. サーバーの内容と設定を採用し, この端末のTray･Memoを別のコピーとして追加しますか? キャンセルすると未保存の編集をこの端末に保持します.', '両方の内容を残す', '競合した編集を別のMemoとして残しました.'),
  'zh-CN': copy('冲突副本', '检查并发更改', '托盘、顺序或删除操作发生冲突。是否保留服务器内容和设置，并另外添加此设备的托盘和备忘录副本？取消会在此设备保留未保存的编辑。', '保留两个版本', '冲突的编辑已保留为独立备忘录副本。'),
  ko: copy('충돌 사본', '동시 변경 확인', '트레이, 순서 또는 삭제 변경이 겹칩니다. 서버 내용과 설정을 유지하고 이 기기의 트레이와 메모를 별도 사본으로 추가할까요? 취소하면 저장하지 않은 편집을 이 기기에 유지합니다.', '두 버전 모두 유지', '충돌한 편집을 별도 메모 사본으로 보존했습니다.'),
  es: copy('Copia en conflicto', 'Revisar cambios simultáneos', 'Hay cambios incompatibles en bandejas, orden o eliminaciones. ¿Conservar el contenido y los ajustes del servidor y añadir copias de las bandejas y notas de este dispositivo? Cancelar mantiene aquí los cambios sin guardar.', 'Conservar ambas versiones', 'Los cambios en conflicto se conservaron como copias separadas.'),
  fr: copy('Copie en conflit', 'Vérifier les modifications simultanées', 'Des modifications de plateaux, d’ordre ou de suppression se chevauchent. Garder le contenu et les réglages du serveur et ajouter des copies des plateaux et notes de cet appareil ? Annuler conserve ici vos modifications non enregistrées.', 'Conserver les deux versions', 'Les modifications en conflit ont été conservées dans des copies séparées.'),
  'pt-BR': copy('Cópia em conflito', 'Revisar alterações simultâneas', 'Há alterações conflitantes em bandejas, ordem ou exclusões. Manter o conteúdo e as configurações do servidor e adicionar cópias das bandejas e notas deste dispositivo? Cancelar mantém aqui as edições não salvas.', 'Manter ambas as versões', 'As edições em conflito foram preservadas em cópias separadas.'),
  hi: copy('टकराव की प्रति', 'एक साथ हुए बदलाव जाँचें', 'ट्रे, क्रम या हटाने के बदलाव टकरा रहे हैं। सर्वर की सामग्री और सेटिंग रखकर इस डिवाइस की ट्रे और मेमो की अलग प्रतियाँ जोड़ें? रद्द करने पर बिना सहेजे संपादन इस डिवाइस पर रहेंगे।', 'दोनों संस्करण रखें', 'टकराने वाले संपादन अलग मेमो प्रतियों में रखे गए।'),
  ar: copy('نسخة تعارض', 'مراجعة التغييرات المتزامنة', 'تتداخل تغييرات الأدراج أو الترتيب أو الحذف. هل تريد الاحتفاظ بمحتوى الخادم وإعداداته وإضافة نسخ منفصلة من أدراج هذا الجهاز وملاحظاته؟ الإلغاء يبقي التعديلات غير المحفوظة على هذا الجهاز.', 'الاحتفاظ بالنسختين', 'حُفظت التعديلات المتعارضة كنسخ منفصلة من الملاحظات.'),
  ru: copy('Конфликтная копия', 'Проверить одновременные изменения', 'Изменения лотков, порядка или удаления конфликтуют. Сохранить содержимое и настройки сервера и добавить отдельные копии лотков и заметок этого устройства? Отмена оставит несохранённые изменения на устройстве.', 'Сохранить обе версии', 'Конфликтующие изменения сохранены в отдельных копиях заметок.'),
  id: copy('Salinan konflik', 'Tinjau perubahan bersamaan', 'Perubahan baki, urutan, atau penghapusan bertentangan. Pertahankan isi dan pengaturan server, lalu tambahkan salinan baki dan memo perangkat ini? Membatalkan akan mempertahankan suntingan yang belum disimpan di perangkat ini.', 'Simpan kedua versi', 'Suntingan yang bertentangan disimpan sebagai salinan memo terpisah.'),
};
